version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: title
        and:
          - or:
              - must_include:
                  regex: '^test-\d+:.+$'
                  message: "Add your issue key"
          - must_exclude:
              regex: ^\[WIP\]
