version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: title
        and:
          - or:
              - must_include:
                  regex: 'test-\d+:.+$'
                  message: "Add your JIRA issue key"
          - must_exclude:
              regex: ^\[WIP\]
      - do: headRef
        must_include:
          regex: "^(fix\/.+|feature\/test-.+|hotfix\/test-.+|release\/.+|develop|staging|main|master)$"
          message: "Check your branch rule name."
