// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"io"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/feature/s3/manager"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"go.uber.org/mock/gomock"
)

// MockAWSS3DownloaderClientInterface is a mock of AWSS3DownloaderClientInterface interface.
type MockAWSS3DownloaderClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAWSS3DownloaderClientInterfaceMockRecorder
	isgomock struct{}
}

// MockAWSS3DownloaderClientInterfaceMockRecorder is the mock recorder for MockAWSS3DownloaderClientInterface.
type MockAWSS3DownloaderClientInterfaceMockRecorder struct {
	mock *MockAWSS3DownloaderClientInterface
}

// NewMockAWSS3DownloaderClientInterface creates a new mock instance.
func NewMockAWSS3DownloaderClientInterface(ctrl *gomock.Controller) *MockAWSS3DownloaderClientInterface {
	mock := &MockAWSS3DownloaderClientInterface{ctrl: ctrl}
	mock.recorder = &MockAWSS3DownloaderClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAWSS3DownloaderClientInterface) EXPECT() *MockAWSS3DownloaderClientInterfaceMockRecorder {
	return m.recorder
}

// Download mocks base method.
func (m *MockAWSS3DownloaderClientInterface) Download(context1 context.Context, writerAt io.WriterAt, getObjectInput *s3.GetObjectInput, fns ...func(*manager.Downloader)) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, writerAt, getObjectInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Download", varargs...)
	n, _ := ret[0].(int64)
	err, _ := ret[1].(error)
	return n, err
}

// Download indicates an expected call of Download.
func (mr *MockAWSS3DownloaderClientInterfaceMockRecorder) Download(context1, writerAt, getObjectInput any,
	fns ...any) *MockAWSS3DownloaderClientInterfaceDownloadCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, writerAt, getObjectInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockAWSS3DownloaderClientInterface)(nil).Download), varargs...)
	return &MockAWSS3DownloaderClientInterfaceDownloadCall{Call: call}
}

// MockAWSS3DownloaderClientInterfaceDownloadCall wrap *gomock.Call
type MockAWSS3DownloaderClientInterfaceDownloadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSS3DownloaderClientInterfaceDownloadCall) Return(n int64, err error) *MockAWSS3DownloaderClientInterfaceDownloadCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSS3DownloaderClientInterfaceDownloadCall) Do(f func(context.Context, io.WriterAt, *s3.GetObjectInput, ...func(*manager.Downloader)) (int64, error)) *MockAWSS3DownloaderClientInterfaceDownloadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSS3DownloaderClientInterfaceDownloadCall) DoAndReturn(f func(context.Context, io.WriterAt, *s3.GetObjectInput, ...func(*manager.Downloader)) (int64, error)) *MockAWSS3DownloaderClientInterfaceDownloadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
