// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs"
	"go.uber.org/mock/gomock"
)

// MockAWSCloudWatchLogsClientInterface is a mock of AWSCloudWatchLogsClientInterface interface.
type MockAWSCloudWatchLogsClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAWSCloudWatchLogsClientInterfaceMockRecorder
	isgomock struct{}
}

// MockAWSCloudWatchLogsClientInterfaceMockRecorder is the mock recorder for MockAWSCloudWatchLogsClientInterface.
type MockAWSCloudWatchLogsClientInterfaceMockRecorder struct {
	mock *MockAWSCloudWatchLogsClientInterface
}

// NewMockAWSCloudWatchLogsClientInterface creates a new mock instance.
func NewMockAWSCloudWatchLogsClientInterface(ctrl *gomock.Controller) *MockAWSCloudWatchLogsClientInterface {
	mock := &MockAWSCloudWatchLogsClientInterface{ctrl: ctrl}
	mock.recorder = &MockAWSCloudWatchLogsClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAWSCloudWatchLogsClientInterface) EXPECT() *MockAWSCloudWatchLogsClientInterfaceMockRecorder {
	return m.recorder
}

// CreateLogGroup mocks base method.
func (m *MockAWSCloudWatchLogsClientInterface) CreateLogGroup(context1 context.Context, createLogGroupInput *cloudwatchlogs.CreateLogGroupInput, fns ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.CreateLogGroupOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, createLogGroupInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateLogGroup", varargs...)
	createLogGroupOutput, _ := ret[0].(*cloudwatchlogs.CreateLogGroupOutput)
	err, _ := ret[1].(error)
	return createLogGroupOutput, err
}

// CreateLogGroup indicates an expected call of CreateLogGroup.
func (mr *MockAWSCloudWatchLogsClientInterfaceMockRecorder) CreateLogGroup(context1, createLogGroupInput any,
	fns ...any) *MockAWSCloudWatchLogsClientInterfaceCreateLogGroupCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, createLogGroupInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLogGroup", reflect.TypeOf((*MockAWSCloudWatchLogsClientInterface)(nil).CreateLogGroup), varargs...)
	return &MockAWSCloudWatchLogsClientInterfaceCreateLogGroupCall{Call: call}
}

// MockAWSCloudWatchLogsClientInterfaceCreateLogGroupCall wrap *gomock.Call
type MockAWSCloudWatchLogsClientInterfaceCreateLogGroupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSCloudWatchLogsClientInterfaceCreateLogGroupCall) Return(createLogGroupOutput *cloudwatchlogs.CreateLogGroupOutput, err error) *MockAWSCloudWatchLogsClientInterfaceCreateLogGroupCall {
	c.Call = c.Call.Return(createLogGroupOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSCloudWatchLogsClientInterfaceCreateLogGroupCall) Do(f func(context.Context, *cloudwatchlogs.CreateLogGroupInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.CreateLogGroupOutput, error)) *MockAWSCloudWatchLogsClientInterfaceCreateLogGroupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSCloudWatchLogsClientInterfaceCreateLogGroupCall) DoAndReturn(f func(context.Context, *cloudwatchlogs.CreateLogGroupInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.CreateLogGroupOutput, error)) *MockAWSCloudWatchLogsClientInterfaceCreateLogGroupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateLogStream mocks base method.
func (m *MockAWSCloudWatchLogsClientInterface) CreateLogStream(context1 context.Context, createLogStreamInput *cloudwatchlogs.CreateLogStreamInput, fns ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.CreateLogStreamOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, createLogStreamInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateLogStream", varargs...)
	createLogStreamOutput, _ := ret[0].(*cloudwatchlogs.CreateLogStreamOutput)
	err, _ := ret[1].(error)
	return createLogStreamOutput, err
}

// CreateLogStream indicates an expected call of CreateLogStream.
func (mr *MockAWSCloudWatchLogsClientInterfaceMockRecorder) CreateLogStream(context1, createLogStreamInput any,
	fns ...any) *MockAWSCloudWatchLogsClientInterfaceCreateLogStreamCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, createLogStreamInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLogStream", reflect.TypeOf((*MockAWSCloudWatchLogsClientInterface)(nil).CreateLogStream), varargs...)
	return &MockAWSCloudWatchLogsClientInterfaceCreateLogStreamCall{Call: call}
}

// MockAWSCloudWatchLogsClientInterfaceCreateLogStreamCall wrap *gomock.Call
type MockAWSCloudWatchLogsClientInterfaceCreateLogStreamCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSCloudWatchLogsClientInterfaceCreateLogStreamCall) Return(createLogStreamOutput *cloudwatchlogs.CreateLogStreamOutput, err error) *MockAWSCloudWatchLogsClientInterfaceCreateLogStreamCall {
	c.Call = c.Call.Return(createLogStreamOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSCloudWatchLogsClientInterfaceCreateLogStreamCall) Do(f func(context.Context, *cloudwatchlogs.CreateLogStreamInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.CreateLogStreamOutput, error)) *MockAWSCloudWatchLogsClientInterfaceCreateLogStreamCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSCloudWatchLogsClientInterfaceCreateLogStreamCall) DoAndReturn(f func(context.Context, *cloudwatchlogs.CreateLogStreamInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.CreateLogStreamOutput, error)) *MockAWSCloudWatchLogsClientInterfaceCreateLogStreamCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DescribeLogGroups mocks base method.
func (m *MockAWSCloudWatchLogsClientInterface) DescribeLogGroups(context1 context.Context, describeLogGroupsInput *cloudwatchlogs.DescribeLogGroupsInput, fns ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.DescribeLogGroupsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, describeLogGroupsInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeLogGroups", varargs...)
	describeLogGroupsOutput, _ := ret[0].(*cloudwatchlogs.DescribeLogGroupsOutput)
	err, _ := ret[1].(error)
	return describeLogGroupsOutput, err
}

// DescribeLogGroups indicates an expected call of DescribeLogGroups.
func (mr *MockAWSCloudWatchLogsClientInterfaceMockRecorder) DescribeLogGroups(context1, describeLogGroupsInput any,
	fns ...any) *MockAWSCloudWatchLogsClientInterfaceDescribeLogGroupsCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, describeLogGroupsInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeLogGroups", reflect.TypeOf((*MockAWSCloudWatchLogsClientInterface)(nil).DescribeLogGroups), varargs...)
	return &MockAWSCloudWatchLogsClientInterfaceDescribeLogGroupsCall{Call: call}
}

// MockAWSCloudWatchLogsClientInterfaceDescribeLogGroupsCall wrap *gomock.Call
type MockAWSCloudWatchLogsClientInterfaceDescribeLogGroupsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSCloudWatchLogsClientInterfaceDescribeLogGroupsCall) Return(describeLogGroupsOutput *cloudwatchlogs.DescribeLogGroupsOutput, err error) *MockAWSCloudWatchLogsClientInterfaceDescribeLogGroupsCall {
	c.Call = c.Call.Return(describeLogGroupsOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSCloudWatchLogsClientInterfaceDescribeLogGroupsCall) Do(f func(context.Context, *cloudwatchlogs.DescribeLogGroupsInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.DescribeLogGroupsOutput, error)) *MockAWSCloudWatchLogsClientInterfaceDescribeLogGroupsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSCloudWatchLogsClientInterfaceDescribeLogGroupsCall) DoAndReturn(f func(context.Context, *cloudwatchlogs.DescribeLogGroupsInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.DescribeLogGroupsOutput, error)) *MockAWSCloudWatchLogsClientInterfaceDescribeLogGroupsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DescribeLogStreams mocks base method.
func (m *MockAWSCloudWatchLogsClientInterface) DescribeLogStreams(context1 context.Context, describeLogStreamsInput *cloudwatchlogs.DescribeLogStreamsInput, fns ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.DescribeLogStreamsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, describeLogStreamsInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeLogStreams", varargs...)
	describeLogStreamsOutput, _ := ret[0].(*cloudwatchlogs.DescribeLogStreamsOutput)
	err, _ := ret[1].(error)
	return describeLogStreamsOutput, err
}

// DescribeLogStreams indicates an expected call of DescribeLogStreams.
func (mr *MockAWSCloudWatchLogsClientInterfaceMockRecorder) DescribeLogStreams(context1, describeLogStreamsInput any,
	fns ...any) *MockAWSCloudWatchLogsClientInterfaceDescribeLogStreamsCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, describeLogStreamsInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeLogStreams", reflect.TypeOf((*MockAWSCloudWatchLogsClientInterface)(nil).DescribeLogStreams), varargs...)
	return &MockAWSCloudWatchLogsClientInterfaceDescribeLogStreamsCall{Call: call}
}

// MockAWSCloudWatchLogsClientInterfaceDescribeLogStreamsCall wrap *gomock.Call
type MockAWSCloudWatchLogsClientInterfaceDescribeLogStreamsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSCloudWatchLogsClientInterfaceDescribeLogStreamsCall) Return(describeLogStreamsOutput *cloudwatchlogs.DescribeLogStreamsOutput, err error) *MockAWSCloudWatchLogsClientInterfaceDescribeLogStreamsCall {
	c.Call = c.Call.Return(describeLogStreamsOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSCloudWatchLogsClientInterfaceDescribeLogStreamsCall) Do(f func(context.Context, *cloudwatchlogs.DescribeLogStreamsInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.DescribeLogStreamsOutput, error)) *MockAWSCloudWatchLogsClientInterfaceDescribeLogStreamsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSCloudWatchLogsClientInterfaceDescribeLogStreamsCall) DoAndReturn(f func(context.Context, *cloudwatchlogs.DescribeLogStreamsInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.DescribeLogStreamsOutput, error)) *MockAWSCloudWatchLogsClientInterfaceDescribeLogStreamsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DescribeMetricFilters mocks base method.
func (m *MockAWSCloudWatchLogsClientInterface) DescribeMetricFilters(context1 context.Context, describeMetricFiltersInput *cloudwatchlogs.DescribeMetricFiltersInput, fns ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.DescribeMetricFiltersOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, describeMetricFiltersInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeMetricFilters", varargs...)
	describeMetricFiltersOutput, _ := ret[0].(*cloudwatchlogs.DescribeMetricFiltersOutput)
	err, _ := ret[1].(error)
	return describeMetricFiltersOutput, err
}

// DescribeMetricFilters indicates an expected call of DescribeMetricFilters.
func (mr *MockAWSCloudWatchLogsClientInterfaceMockRecorder) DescribeMetricFilters(context1, describeMetricFiltersInput any,
	fns ...any) *MockAWSCloudWatchLogsClientInterfaceDescribeMetricFiltersCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, describeMetricFiltersInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeMetricFilters", reflect.TypeOf((*MockAWSCloudWatchLogsClientInterface)(nil).DescribeMetricFilters), varargs...)
	return &MockAWSCloudWatchLogsClientInterfaceDescribeMetricFiltersCall{Call: call}
}

// MockAWSCloudWatchLogsClientInterfaceDescribeMetricFiltersCall wrap *gomock.Call
type MockAWSCloudWatchLogsClientInterfaceDescribeMetricFiltersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSCloudWatchLogsClientInterfaceDescribeMetricFiltersCall) Return(describeMetricFiltersOutput *cloudwatchlogs.DescribeMetricFiltersOutput, err error) *MockAWSCloudWatchLogsClientInterfaceDescribeMetricFiltersCall {
	c.Call = c.Call.Return(describeMetricFiltersOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSCloudWatchLogsClientInterfaceDescribeMetricFiltersCall) Do(f func(context.Context, *cloudwatchlogs.DescribeMetricFiltersInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.DescribeMetricFiltersOutput, error)) *MockAWSCloudWatchLogsClientInterfaceDescribeMetricFiltersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSCloudWatchLogsClientInterfaceDescribeMetricFiltersCall) DoAndReturn(f func(context.Context, *cloudwatchlogs.DescribeMetricFiltersInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.DescribeMetricFiltersOutput, error)) *MockAWSCloudWatchLogsClientInterfaceDescribeMetricFiltersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FilterLogEvents mocks base method.
func (m *MockAWSCloudWatchLogsClientInterface) FilterLogEvents(context1 context.Context, filterLogEventsInput *cloudwatchlogs.FilterLogEventsInput, fns ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.FilterLogEventsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, filterLogEventsInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FilterLogEvents", varargs...)
	filterLogEventsOutput, _ := ret[0].(*cloudwatchlogs.FilterLogEventsOutput)
	err, _ := ret[1].(error)
	return filterLogEventsOutput, err
}

// FilterLogEvents indicates an expected call of FilterLogEvents.
func (mr *MockAWSCloudWatchLogsClientInterfaceMockRecorder) FilterLogEvents(context1, filterLogEventsInput any,
	fns ...any) *MockAWSCloudWatchLogsClientInterfaceFilterLogEventsCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, filterLogEventsInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterLogEvents", reflect.TypeOf((*MockAWSCloudWatchLogsClientInterface)(nil).FilterLogEvents), varargs...)
	return &MockAWSCloudWatchLogsClientInterfaceFilterLogEventsCall{Call: call}
}

// MockAWSCloudWatchLogsClientInterfaceFilterLogEventsCall wrap *gomock.Call
type MockAWSCloudWatchLogsClientInterfaceFilterLogEventsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSCloudWatchLogsClientInterfaceFilterLogEventsCall) Return(filterLogEventsOutput *cloudwatchlogs.FilterLogEventsOutput, err error) *MockAWSCloudWatchLogsClientInterfaceFilterLogEventsCall {
	c.Call = c.Call.Return(filterLogEventsOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSCloudWatchLogsClientInterfaceFilterLogEventsCall) Do(f func(context.Context, *cloudwatchlogs.FilterLogEventsInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.FilterLogEventsOutput, error)) *MockAWSCloudWatchLogsClientInterfaceFilterLogEventsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSCloudWatchLogsClientInterfaceFilterLogEventsCall) DoAndReturn(f func(context.Context, *cloudwatchlogs.FilterLogEventsInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.FilterLogEventsOutput, error)) *MockAWSCloudWatchLogsClientInterfaceFilterLogEventsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PutLogEvents mocks base method.
func (m *MockAWSCloudWatchLogsClientInterface) PutLogEvents(context1 context.Context, putLogEventsInput *cloudwatchlogs.PutLogEventsInput, fns ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.PutLogEventsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, putLogEventsInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutLogEvents", varargs...)
	putLogEventsOutput, _ := ret[0].(*cloudwatchlogs.PutLogEventsOutput)
	err, _ := ret[1].(error)
	return putLogEventsOutput, err
}

// PutLogEvents indicates an expected call of PutLogEvents.
func (mr *MockAWSCloudWatchLogsClientInterfaceMockRecorder) PutLogEvents(context1, putLogEventsInput any,
	fns ...any) *MockAWSCloudWatchLogsClientInterfacePutLogEventsCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, putLogEventsInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutLogEvents", reflect.TypeOf((*MockAWSCloudWatchLogsClientInterface)(nil).PutLogEvents), varargs...)
	return &MockAWSCloudWatchLogsClientInterfacePutLogEventsCall{Call: call}
}

// MockAWSCloudWatchLogsClientInterfacePutLogEventsCall wrap *gomock.Call
type MockAWSCloudWatchLogsClientInterfacePutLogEventsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSCloudWatchLogsClientInterfacePutLogEventsCall) Return(putLogEventsOutput *cloudwatchlogs.PutLogEventsOutput, err error) *MockAWSCloudWatchLogsClientInterfacePutLogEventsCall {
	c.Call = c.Call.Return(putLogEventsOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSCloudWatchLogsClientInterfacePutLogEventsCall) Do(f func(context.Context, *cloudwatchlogs.PutLogEventsInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.PutLogEventsOutput, error)) *MockAWSCloudWatchLogsClientInterfacePutLogEventsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSCloudWatchLogsClientInterfacePutLogEventsCall) DoAndReturn(f func(context.Context, *cloudwatchlogs.PutLogEventsInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.PutLogEventsOutput, error)) *MockAWSCloudWatchLogsClientInterfacePutLogEventsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PutRetentionPolicy mocks base method.
func (m *MockAWSCloudWatchLogsClientInterface) PutRetentionPolicy(context1 context.Context, putRetentionPolicyInput *cloudwatchlogs.PutRetentionPolicyInput, fns ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.PutRetentionPolicyOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, putRetentionPolicyInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutRetentionPolicy", varargs...)
	putRetentionPolicyOutput, _ := ret[0].(*cloudwatchlogs.PutRetentionPolicyOutput)
	err, _ := ret[1].(error)
	return putRetentionPolicyOutput, err
}

// PutRetentionPolicy indicates an expected call of PutRetentionPolicy.
func (mr *MockAWSCloudWatchLogsClientInterfaceMockRecorder) PutRetentionPolicy(context1, putRetentionPolicyInput any,
	fns ...any) *MockAWSCloudWatchLogsClientInterfacePutRetentionPolicyCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, putRetentionPolicyInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutRetentionPolicy", reflect.TypeOf((*MockAWSCloudWatchLogsClientInterface)(nil).PutRetentionPolicy), varargs...)
	return &MockAWSCloudWatchLogsClientInterfacePutRetentionPolicyCall{Call: call}
}

// MockAWSCloudWatchLogsClientInterfacePutRetentionPolicyCall wrap *gomock.Call
type MockAWSCloudWatchLogsClientInterfacePutRetentionPolicyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSCloudWatchLogsClientInterfacePutRetentionPolicyCall) Return(putRetentionPolicyOutput *cloudwatchlogs.PutRetentionPolicyOutput, err error) *MockAWSCloudWatchLogsClientInterfacePutRetentionPolicyCall {
	c.Call = c.Call.Return(putRetentionPolicyOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSCloudWatchLogsClientInterfacePutRetentionPolicyCall) Do(f func(context.Context, *cloudwatchlogs.PutRetentionPolicyInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.PutRetentionPolicyOutput, error)) *MockAWSCloudWatchLogsClientInterfacePutRetentionPolicyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSCloudWatchLogsClientInterfacePutRetentionPolicyCall) DoAndReturn(f func(context.Context, *cloudwatchlogs.PutRetentionPolicyInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.PutRetentionPolicyOutput, error)) *MockAWSCloudWatchLogsClientInterfacePutRetentionPolicyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
