// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/service/s3"
	"go.uber.org/mock/gomock"
)

// MockAWSS3ClientInterface is a mock of AWSS3ClientInterface interface.
type MockAWSS3ClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAWSS3ClientInterfaceMockRecorder
	isgomock struct{}
}

// MockAWSS3ClientInterfaceMockRecorder is the mock recorder for MockAWSS3ClientInterface.
type MockAWSS3ClientInterfaceMockRecorder struct {
	mock *MockAWSS3ClientInterface
}

// NewMockAWSS3ClientInterface creates a new mock instance.
func NewMockAWSS3ClientInterface(ctrl *gomock.Controller) *MockAWSS3ClientInterface {
	mock := &MockAWSS3ClientInterface{ctrl: ctrl}
	mock.recorder = &MockAWSS3ClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAWSS3ClientInterface) EXPECT() *MockAWSS3ClientInterfaceMockRecorder {
	return m.recorder
}

// CreateBucket mocks base method.
func (m *MockAWSS3ClientInterface) CreateBucket(context1 context.Context, createBucketInput *s3.CreateBucketInput, fns ...func(*s3.Options)) (*s3.CreateBucketOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, createBucketInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateBucket", varargs...)
	createBucketOutput, _ := ret[0].(*s3.CreateBucketOutput)
	err, _ := ret[1].(error)
	return createBucketOutput, err
}

// CreateBucket indicates an expected call of CreateBucket.
func (mr *MockAWSS3ClientInterfaceMockRecorder) CreateBucket(context1, createBucketInput any,
	fns ...any) *MockAWSS3ClientInterfaceCreateBucketCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, createBucketInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBucket", reflect.TypeOf((*MockAWSS3ClientInterface)(nil).CreateBucket), varargs...)
	return &MockAWSS3ClientInterfaceCreateBucketCall{Call: call}
}

// MockAWSS3ClientInterfaceCreateBucketCall wrap *gomock.Call
type MockAWSS3ClientInterfaceCreateBucketCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSS3ClientInterfaceCreateBucketCall) Return(createBucketOutput *s3.CreateBucketOutput, err error) *MockAWSS3ClientInterfaceCreateBucketCall {
	c.Call = c.Call.Return(createBucketOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSS3ClientInterfaceCreateBucketCall) Do(f func(context.Context, *s3.CreateBucketInput, ...func(*s3.Options)) (*s3.CreateBucketOutput, error)) *MockAWSS3ClientInterfaceCreateBucketCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSS3ClientInterfaceCreateBucketCall) DoAndReturn(f func(context.Context, *s3.CreateBucketInput, ...func(*s3.Options)) (*s3.CreateBucketOutput, error)) *MockAWSS3ClientInterfaceCreateBucketCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteBucket mocks base method.
func (m *MockAWSS3ClientInterface) DeleteBucket(context1 context.Context, deleteBucketInput *s3.DeleteBucketInput, fns ...func(*s3.Options)) (*s3.DeleteBucketOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, deleteBucketInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteBucket", varargs...)
	deleteBucketOutput, _ := ret[0].(*s3.DeleteBucketOutput)
	err, _ := ret[1].(error)
	return deleteBucketOutput, err
}

// DeleteBucket indicates an expected call of DeleteBucket.
func (mr *MockAWSS3ClientInterfaceMockRecorder) DeleteBucket(context1, deleteBucketInput any,
	fns ...any) *MockAWSS3ClientInterfaceDeleteBucketCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, deleteBucketInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBucket", reflect.TypeOf((*MockAWSS3ClientInterface)(nil).DeleteBucket), varargs...)
	return &MockAWSS3ClientInterfaceDeleteBucketCall{Call: call}
}

// MockAWSS3ClientInterfaceDeleteBucketCall wrap *gomock.Call
type MockAWSS3ClientInterfaceDeleteBucketCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSS3ClientInterfaceDeleteBucketCall) Return(deleteBucketOutput *s3.DeleteBucketOutput, err error) *MockAWSS3ClientInterfaceDeleteBucketCall {
	c.Call = c.Call.Return(deleteBucketOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSS3ClientInterfaceDeleteBucketCall) Do(f func(context.Context, *s3.DeleteBucketInput, ...func(*s3.Options)) (*s3.DeleteBucketOutput, error)) *MockAWSS3ClientInterfaceDeleteBucketCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSS3ClientInterfaceDeleteBucketCall) DoAndReturn(f func(context.Context, *s3.DeleteBucketInput, ...func(*s3.Options)) (*s3.DeleteBucketOutput, error)) *MockAWSS3ClientInterfaceDeleteBucketCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteObject mocks base method.
func (m *MockAWSS3ClientInterface) DeleteObject(context1 context.Context, deleteObjectInput *s3.DeleteObjectInput, fns ...func(*s3.Options)) (*s3.DeleteObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, deleteObjectInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteObject", varargs...)
	deleteObjectOutput, _ := ret[0].(*s3.DeleteObjectOutput)
	err, _ := ret[1].(error)
	return deleteObjectOutput, err
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockAWSS3ClientInterfaceMockRecorder) DeleteObject(context1, deleteObjectInput any,
	fns ...any) *MockAWSS3ClientInterfaceDeleteObjectCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, deleteObjectInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockAWSS3ClientInterface)(nil).DeleteObject), varargs...)
	return &MockAWSS3ClientInterfaceDeleteObjectCall{Call: call}
}

// MockAWSS3ClientInterfaceDeleteObjectCall wrap *gomock.Call
type MockAWSS3ClientInterfaceDeleteObjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSS3ClientInterfaceDeleteObjectCall) Return(deleteObjectOutput *s3.DeleteObjectOutput, err error) *MockAWSS3ClientInterfaceDeleteObjectCall {
	c.Call = c.Call.Return(deleteObjectOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSS3ClientInterfaceDeleteObjectCall) Do(f func(context.Context, *s3.DeleteObjectInput, ...func(*s3.Options)) (*s3.DeleteObjectOutput, error)) *MockAWSS3ClientInterfaceDeleteObjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSS3ClientInterfaceDeleteObjectCall) DoAndReturn(f func(context.Context, *s3.DeleteObjectInput, ...func(*s3.Options)) (*s3.DeleteObjectOutput, error)) *MockAWSS3ClientInterfaceDeleteObjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteObjects mocks base method.
func (m *MockAWSS3ClientInterface) DeleteObjects(context1 context.Context, deleteObjectsInput *s3.DeleteObjectsInput, fns ...func(*s3.Options)) (*s3.DeleteObjectsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, deleteObjectsInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteObjects", varargs...)
	deleteObjectsOutput, _ := ret[0].(*s3.DeleteObjectsOutput)
	err, _ := ret[1].(error)
	return deleteObjectsOutput, err
}

// DeleteObjects indicates an expected call of DeleteObjects.
func (mr *MockAWSS3ClientInterfaceMockRecorder) DeleteObjects(context1, deleteObjectsInput any,
	fns ...any) *MockAWSS3ClientInterfaceDeleteObjectsCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, deleteObjectsInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjects", reflect.TypeOf((*MockAWSS3ClientInterface)(nil).DeleteObjects), varargs...)
	return &MockAWSS3ClientInterfaceDeleteObjectsCall{Call: call}
}

// MockAWSS3ClientInterfaceDeleteObjectsCall wrap *gomock.Call
type MockAWSS3ClientInterfaceDeleteObjectsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSS3ClientInterfaceDeleteObjectsCall) Return(deleteObjectsOutput *s3.DeleteObjectsOutput, err error) *MockAWSS3ClientInterfaceDeleteObjectsCall {
	c.Call = c.Call.Return(deleteObjectsOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSS3ClientInterfaceDeleteObjectsCall) Do(f func(context.Context, *s3.DeleteObjectsInput, ...func(*s3.Options)) (*s3.DeleteObjectsOutput, error)) *MockAWSS3ClientInterfaceDeleteObjectsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSS3ClientInterfaceDeleteObjectsCall) DoAndReturn(f func(context.Context, *s3.DeleteObjectsInput, ...func(*s3.Options)) (*s3.DeleteObjectsOutput, error)) *MockAWSS3ClientInterfaceDeleteObjectsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetObject mocks base method.
func (m *MockAWSS3ClientInterface) GetObject(context1 context.Context, getObjectInput *s3.GetObjectInput, fns ...func(*s3.Options)) (*s3.GetObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, getObjectInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetObject", varargs...)
	getObjectOutput, _ := ret[0].(*s3.GetObjectOutput)
	err, _ := ret[1].(error)
	return getObjectOutput, err
}

// GetObject indicates an expected call of GetObject.
func (mr *MockAWSS3ClientInterfaceMockRecorder) GetObject(context1, getObjectInput any,
	fns ...any) *MockAWSS3ClientInterfaceGetObjectCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, getObjectInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockAWSS3ClientInterface)(nil).GetObject), varargs...)
	return &MockAWSS3ClientInterfaceGetObjectCall{Call: call}
}

// MockAWSS3ClientInterfaceGetObjectCall wrap *gomock.Call
type MockAWSS3ClientInterfaceGetObjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSS3ClientInterfaceGetObjectCall) Return(getObjectOutput *s3.GetObjectOutput, err error) *MockAWSS3ClientInterfaceGetObjectCall {
	c.Call = c.Call.Return(getObjectOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSS3ClientInterfaceGetObjectCall) Do(f func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) (*s3.GetObjectOutput, error)) *MockAWSS3ClientInterfaceGetObjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSS3ClientInterfaceGetObjectCall) DoAndReturn(f func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) (*s3.GetObjectOutput, error)) *MockAWSS3ClientInterfaceGetObjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListBuckets mocks base method.
func (m *MockAWSS3ClientInterface) ListBuckets(context1 context.Context, listBucketsInput *s3.ListBucketsInput, fns ...func(*s3.Options)) (*s3.ListBucketsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, listBucketsInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListBuckets", varargs...)
	listBucketsOutput, _ := ret[0].(*s3.ListBucketsOutput)
	err, _ := ret[1].(error)
	return listBucketsOutput, err
}

// ListBuckets indicates an expected call of ListBuckets.
func (mr *MockAWSS3ClientInterfaceMockRecorder) ListBuckets(context1, listBucketsInput any,
	fns ...any) *MockAWSS3ClientInterfaceListBucketsCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, listBucketsInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBuckets", reflect.TypeOf((*MockAWSS3ClientInterface)(nil).ListBuckets), varargs...)
	return &MockAWSS3ClientInterfaceListBucketsCall{Call: call}
}

// MockAWSS3ClientInterfaceListBucketsCall wrap *gomock.Call
type MockAWSS3ClientInterfaceListBucketsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSS3ClientInterfaceListBucketsCall) Return(listBucketsOutput *s3.ListBucketsOutput, err error) *MockAWSS3ClientInterfaceListBucketsCall {
	c.Call = c.Call.Return(listBucketsOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSS3ClientInterfaceListBucketsCall) Do(f func(context.Context, *s3.ListBucketsInput, ...func(*s3.Options)) (*s3.ListBucketsOutput, error)) *MockAWSS3ClientInterfaceListBucketsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSS3ClientInterfaceListBucketsCall) DoAndReturn(f func(context.Context, *s3.ListBucketsInput, ...func(*s3.Options)) (*s3.ListBucketsOutput, error)) *MockAWSS3ClientInterfaceListBucketsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListObjectsV2 mocks base method.
func (m *MockAWSS3ClientInterface) ListObjectsV2(context1 context.Context, listObjectsV2Input *s3.ListObjectsV2Input, fns ...func(*s3.Options)) (*s3.ListObjectsV2Output, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, listObjectsV2Input}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListObjectsV2", varargs...)
	listObjectsV2Output, _ := ret[0].(*s3.ListObjectsV2Output)
	err, _ := ret[1].(error)
	return listObjectsV2Output, err
}

// ListObjectsV2 indicates an expected call of ListObjectsV2.
func (mr *MockAWSS3ClientInterfaceMockRecorder) ListObjectsV2(context1, listObjectsV2Input any,
	fns ...any) *MockAWSS3ClientInterfaceListObjectsV2Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, listObjectsV2Input}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectsV2", reflect.TypeOf((*MockAWSS3ClientInterface)(nil).ListObjectsV2), varargs...)
	return &MockAWSS3ClientInterfaceListObjectsV2Call{Call: call}
}

// MockAWSS3ClientInterfaceListObjectsV2Call wrap *gomock.Call
type MockAWSS3ClientInterfaceListObjectsV2Call struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSS3ClientInterfaceListObjectsV2Call) Return(listObjectsV2Output *s3.ListObjectsV2Output, err error) *MockAWSS3ClientInterfaceListObjectsV2Call {
	c.Call = c.Call.Return(listObjectsV2Output, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSS3ClientInterfaceListObjectsV2Call) Do(f func(context.Context, *s3.ListObjectsV2Input, ...func(*s3.Options)) (*s3.ListObjectsV2Output, error)) *MockAWSS3ClientInterfaceListObjectsV2Call {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSS3ClientInterfaceListObjectsV2Call) DoAndReturn(f func(context.Context, *s3.ListObjectsV2Input, ...func(*s3.Options)) (*s3.ListObjectsV2Output, error)) *MockAWSS3ClientInterfaceListObjectsV2Call {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PutObject mocks base method.
func (m *MockAWSS3ClientInterface) PutObject(context1 context.Context, putObjectInput *s3.PutObjectInput, fns ...func(*s3.Options)) (*s3.PutObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, putObjectInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutObject", varargs...)
	putObjectOutput, _ := ret[0].(*s3.PutObjectOutput)
	err, _ := ret[1].(error)
	return putObjectOutput, err
}

// PutObject indicates an expected call of PutObject.
func (mr *MockAWSS3ClientInterfaceMockRecorder) PutObject(context1, putObjectInput any,
	fns ...any) *MockAWSS3ClientInterfacePutObjectCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, putObjectInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockAWSS3ClientInterface)(nil).PutObject), varargs...)
	return &MockAWSS3ClientInterfacePutObjectCall{Call: call}
}

// MockAWSS3ClientInterfacePutObjectCall wrap *gomock.Call
type MockAWSS3ClientInterfacePutObjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSS3ClientInterfacePutObjectCall) Return(putObjectOutput *s3.PutObjectOutput, err error) *MockAWSS3ClientInterfacePutObjectCall {
	c.Call = c.Call.Return(putObjectOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSS3ClientInterfacePutObjectCall) Do(f func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) (*s3.PutObjectOutput, error)) *MockAWSS3ClientInterfacePutObjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSS3ClientInterfacePutObjectCall) DoAndReturn(f func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) (*s3.PutObjectOutput, error)) *MockAWSS3ClientInterfacePutObjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
