// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/service/sts"
	"go.uber.org/mock/gomock"
)

// MockAWSSTSClientInterface is a mock of AWSSTSClientInterface interface.
type MockAWSSTSClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAWSSTSClientInterfaceMockRecorder
	isgomock struct{}
}

// MockAWSSTSClientInterfaceMockRecorder is the mock recorder for MockAWSSTSClientInterface.
type MockAWSSTSClientInterfaceMockRecorder struct {
	mock *MockAWSSTSClientInterface
}

// NewMockAWSSTSClientInterface creates a new mock instance.
func NewMockAWSSTSClientInterface(ctrl *gomock.Controller) *MockAWSSTSClientInterface {
	mock := &MockAWSSTSClientInterface{ctrl: ctrl}
	mock.recorder = &MockAWSSTSClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAWSSTSClientInterface) EXPECT() *MockAWSSTSClientInterfaceMockRecorder {
	return m.recorder
}

// GetAccessKeyInfo mocks base method.
func (m *MockAWSSTSClientInterface) GetAccessKeyInfo(context1 context.Context, getAccessKeyInfoInput *sts.GetAccessKeyInfoInput, fns ...func(*sts.Options)) (*sts.GetAccessKeyInfoOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, getAccessKeyInfoInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAccessKeyInfo", varargs...)
	getAccessKeyInfoOutput, _ := ret[0].(*sts.GetAccessKeyInfoOutput)
	err, _ := ret[1].(error)
	return getAccessKeyInfoOutput, err
}

// GetAccessKeyInfo indicates an expected call of GetAccessKeyInfo.
func (mr *MockAWSSTSClientInterfaceMockRecorder) GetAccessKeyInfo(context1, getAccessKeyInfoInput any,
	fns ...any) *MockAWSSTSClientInterfaceGetAccessKeyInfoCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, getAccessKeyInfoInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessKeyInfo", reflect.TypeOf((*MockAWSSTSClientInterface)(nil).GetAccessKeyInfo), varargs...)
	return &MockAWSSTSClientInterfaceGetAccessKeyInfoCall{Call: call}
}

// MockAWSSTSClientInterfaceGetAccessKeyInfoCall wrap *gomock.Call
type MockAWSSTSClientInterfaceGetAccessKeyInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSSTSClientInterfaceGetAccessKeyInfoCall) Return(getAccessKeyInfoOutput *sts.GetAccessKeyInfoOutput, err error) *MockAWSSTSClientInterfaceGetAccessKeyInfoCall {
	c.Call = c.Call.Return(getAccessKeyInfoOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSSTSClientInterfaceGetAccessKeyInfoCall) Do(f func(context.Context, *sts.GetAccessKeyInfoInput, ...func(*sts.Options)) (*sts.GetAccessKeyInfoOutput, error)) *MockAWSSTSClientInterfaceGetAccessKeyInfoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSSTSClientInterfaceGetAccessKeyInfoCall) DoAndReturn(f func(context.Context, *sts.GetAccessKeyInfoInput, ...func(*sts.Options)) (*sts.GetAccessKeyInfoOutput, error)) *MockAWSSTSClientInterfaceGetAccessKeyInfoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetCallerIdentity mocks base method.
func (m *MockAWSSTSClientInterface) GetCallerIdentity(context1 context.Context, getCallerIdentityInput *sts.GetCallerIdentityInput, fns ...func(*sts.Options)) (*sts.GetCallerIdentityOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, getCallerIdentityInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCallerIdentity", varargs...)
	getCallerIdentityOutput, _ := ret[0].(*sts.GetCallerIdentityOutput)
	err, _ := ret[1].(error)
	return getCallerIdentityOutput, err
}

// GetCallerIdentity indicates an expected call of GetCallerIdentity.
func (mr *MockAWSSTSClientInterfaceMockRecorder) GetCallerIdentity(context1, getCallerIdentityInput any,
	fns ...any) *MockAWSSTSClientInterfaceGetCallerIdentityCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, getCallerIdentityInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCallerIdentity", reflect.TypeOf((*MockAWSSTSClientInterface)(nil).GetCallerIdentity), varargs...)
	return &MockAWSSTSClientInterfaceGetCallerIdentityCall{Call: call}
}

// MockAWSSTSClientInterfaceGetCallerIdentityCall wrap *gomock.Call
type MockAWSSTSClientInterfaceGetCallerIdentityCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSSTSClientInterfaceGetCallerIdentityCall) Return(getCallerIdentityOutput *sts.GetCallerIdentityOutput, err error) *MockAWSSTSClientInterfaceGetCallerIdentityCall {
	c.Call = c.Call.Return(getCallerIdentityOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSSTSClientInterfaceGetCallerIdentityCall) Do(f func(context.Context, *sts.GetCallerIdentityInput, ...func(*sts.Options)) (*sts.GetCallerIdentityOutput, error)) *MockAWSSTSClientInterfaceGetCallerIdentityCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSSTSClientInterfaceGetCallerIdentityCall) DoAndReturn(f func(context.Context, *sts.GetCallerIdentityInput, ...func(*sts.Options)) (*sts.GetCallerIdentityOutput, error)) *MockAWSSTSClientInterfaceGetCallerIdentityCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDelegatedAccessToken mocks base method.
func (m *MockAWSSTSClientInterface) GetDelegatedAccessToken(context1 context.Context, getDelegatedAccessTokenInput *sts.GetDelegatedAccessTokenInput, fns ...func(*sts.Options)) (*sts.GetDelegatedAccessTokenOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, getDelegatedAccessTokenInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDelegatedAccessToken", varargs...)
	getDelegatedAccessTokenOutput, _ := ret[0].(*sts.GetDelegatedAccessTokenOutput)
	err, _ := ret[1].(error)
	return getDelegatedAccessTokenOutput, err
}

// GetDelegatedAccessToken indicates an expected call of GetDelegatedAccessToken.
func (mr *MockAWSSTSClientInterfaceMockRecorder) GetDelegatedAccessToken(context1, getDelegatedAccessTokenInput any,
	fns ...any) *MockAWSSTSClientInterfaceGetDelegatedAccessTokenCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, getDelegatedAccessTokenInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDelegatedAccessToken", reflect.TypeOf((*MockAWSSTSClientInterface)(nil).GetDelegatedAccessToken), varargs...)
	return &MockAWSSTSClientInterfaceGetDelegatedAccessTokenCall{Call: call}
}

// MockAWSSTSClientInterfaceGetDelegatedAccessTokenCall wrap *gomock.Call
type MockAWSSTSClientInterfaceGetDelegatedAccessTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSSTSClientInterfaceGetDelegatedAccessTokenCall) Return(getDelegatedAccessTokenOutput *sts.GetDelegatedAccessTokenOutput, err error) *MockAWSSTSClientInterfaceGetDelegatedAccessTokenCall {
	c.Call = c.Call.Return(getDelegatedAccessTokenOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSSTSClientInterfaceGetDelegatedAccessTokenCall) Do(f func(context.Context, *sts.GetDelegatedAccessTokenInput, ...func(*sts.Options)) (*sts.GetDelegatedAccessTokenOutput, error)) *MockAWSSTSClientInterfaceGetDelegatedAccessTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSSTSClientInterfaceGetDelegatedAccessTokenCall) DoAndReturn(f func(context.Context, *sts.GetDelegatedAccessTokenInput, ...func(*sts.Options)) (*sts.GetDelegatedAccessTokenOutput, error)) *MockAWSSTSClientInterfaceGetDelegatedAccessTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetFederationToken mocks base method.
func (m *MockAWSSTSClientInterface) GetFederationToken(context1 context.Context, getFederationTokenInput *sts.GetFederationTokenInput, fns ...func(*sts.Options)) (*sts.GetFederationTokenOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, getFederationTokenInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFederationToken", varargs...)
	getFederationTokenOutput, _ := ret[0].(*sts.GetFederationTokenOutput)
	err, _ := ret[1].(error)
	return getFederationTokenOutput, err
}

// GetFederationToken indicates an expected call of GetFederationToken.
func (mr *MockAWSSTSClientInterfaceMockRecorder) GetFederationToken(context1, getFederationTokenInput any,
	fns ...any) *MockAWSSTSClientInterfaceGetFederationTokenCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, getFederationTokenInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFederationToken", reflect.TypeOf((*MockAWSSTSClientInterface)(nil).GetFederationToken), varargs...)
	return &MockAWSSTSClientInterfaceGetFederationTokenCall{Call: call}
}

// MockAWSSTSClientInterfaceGetFederationTokenCall wrap *gomock.Call
type MockAWSSTSClientInterfaceGetFederationTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSSTSClientInterfaceGetFederationTokenCall) Return(getFederationTokenOutput *sts.GetFederationTokenOutput, err error) *MockAWSSTSClientInterfaceGetFederationTokenCall {
	c.Call = c.Call.Return(getFederationTokenOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSSTSClientInterfaceGetFederationTokenCall) Do(f func(context.Context, *sts.GetFederationTokenInput, ...func(*sts.Options)) (*sts.GetFederationTokenOutput, error)) *MockAWSSTSClientInterfaceGetFederationTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSSTSClientInterfaceGetFederationTokenCall) DoAndReturn(f func(context.Context, *sts.GetFederationTokenInput, ...func(*sts.Options)) (*sts.GetFederationTokenOutput, error)) *MockAWSSTSClientInterfaceGetFederationTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSessionToken mocks base method.
func (m *MockAWSSTSClientInterface) GetSessionToken(context1 context.Context, getSessionTokenInput *sts.GetSessionTokenInput, fns ...func(*sts.Options)) (*sts.GetSessionTokenOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, getSessionTokenInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSessionToken", varargs...)
	getSessionTokenOutput, _ := ret[0].(*sts.GetSessionTokenOutput)
	err, _ := ret[1].(error)
	return getSessionTokenOutput, err
}

// GetSessionToken indicates an expected call of GetSessionToken.
func (mr *MockAWSSTSClientInterfaceMockRecorder) GetSessionToken(context1, getSessionTokenInput any,
	fns ...any) *MockAWSSTSClientInterfaceGetSessionTokenCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, getSessionTokenInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionToken", reflect.TypeOf((*MockAWSSTSClientInterface)(nil).GetSessionToken), varargs...)
	return &MockAWSSTSClientInterfaceGetSessionTokenCall{Call: call}
}

// MockAWSSTSClientInterfaceGetSessionTokenCall wrap *gomock.Call
type MockAWSSTSClientInterfaceGetSessionTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSSTSClientInterfaceGetSessionTokenCall) Return(getSessionTokenOutput *sts.GetSessionTokenOutput, err error) *MockAWSSTSClientInterfaceGetSessionTokenCall {
	c.Call = c.Call.Return(getSessionTokenOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSSTSClientInterfaceGetSessionTokenCall) Do(f func(context.Context, *sts.GetSessionTokenInput, ...func(*sts.Options)) (*sts.GetSessionTokenOutput, error)) *MockAWSSTSClientInterfaceGetSessionTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSSTSClientInterfaceGetSessionTokenCall) DoAndReturn(f func(context.Context, *sts.GetSessionTokenInput, ...func(*sts.Options)) (*sts.GetSessionTokenOutput, error)) *MockAWSSTSClientInterfaceGetSessionTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetWebIdentityToken mocks base method.
func (m *MockAWSSTSClientInterface) GetWebIdentityToken(context1 context.Context, getWebIdentityTokenInput *sts.GetWebIdentityTokenInput, fns ...func(*sts.Options)) (*sts.GetWebIdentityTokenOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, getWebIdentityTokenInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetWebIdentityToken", varargs...)
	getWebIdentityTokenOutput, _ := ret[0].(*sts.GetWebIdentityTokenOutput)
	err, _ := ret[1].(error)
	return getWebIdentityTokenOutput, err
}

// GetWebIdentityToken indicates an expected call of GetWebIdentityToken.
func (mr *MockAWSSTSClientInterfaceMockRecorder) GetWebIdentityToken(context1, getWebIdentityTokenInput any,
	fns ...any) *MockAWSSTSClientInterfaceGetWebIdentityTokenCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, getWebIdentityTokenInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebIdentityToken", reflect.TypeOf((*MockAWSSTSClientInterface)(nil).GetWebIdentityToken), varargs...)
	return &MockAWSSTSClientInterfaceGetWebIdentityTokenCall{Call: call}
}

// MockAWSSTSClientInterfaceGetWebIdentityTokenCall wrap *gomock.Call
type MockAWSSTSClientInterfaceGetWebIdentityTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSSTSClientInterfaceGetWebIdentityTokenCall) Return(getWebIdentityTokenOutput *sts.GetWebIdentityTokenOutput, err error) *MockAWSSTSClientInterfaceGetWebIdentityTokenCall {
	c.Call = c.Call.Return(getWebIdentityTokenOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSSTSClientInterfaceGetWebIdentityTokenCall) Do(f func(context.Context, *sts.GetWebIdentityTokenInput, ...func(*sts.Options)) (*sts.GetWebIdentityTokenOutput, error)) *MockAWSSTSClientInterfaceGetWebIdentityTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSSTSClientInterfaceGetWebIdentityTokenCall) DoAndReturn(f func(context.Context, *sts.GetWebIdentityTokenInput, ...func(*sts.Options)) (*sts.GetWebIdentityTokenOutput, error)) *MockAWSSTSClientInterfaceGetWebIdentityTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
