// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"
	"time"

	"github.com/redis/go-redis/v9"
	"go.uber.org/mock/gomock"
)

// MockRedisClientInterface is a mock of RedisClientInterface interface.
type MockRedisClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRedisClientInterfaceMockRecorder
	isgomock struct{}
}

// MockRedisClientInterfaceMockRecorder is the mock recorder for MockRedisClientInterface.
type MockRedisClientInterfaceMockRecorder struct {
	mock *MockRedisClientInterface
}

// NewMockRedisClientInterface creates a new mock instance.
func NewMockRedisClientInterface(ctrl *gomock.Controller) *MockRedisClientInterface {
	mock := &MockRedisClientInterface{ctrl: ctrl}
	mock.recorder = &MockRedisClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisClientInterface) EXPECT() *MockRedisClientInterfaceMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockRedisClientInterface) Append(context1 context.Context, s string, s1 string) *redis.IntCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", context1, s, s1)
	intCmd, _ := ret[0].(*redis.IntCmd)
	return intCmd
}

// Append indicates an expected call of Append.
func (mr *MockRedisClientInterfaceMockRecorder) Append(context1, s, s1 any) *MockRedisClientInterfaceAppendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockRedisClientInterface)(nil).Append), context1, s, s1)
	return &MockRedisClientInterfaceAppendCall{Call: call}
}

// MockRedisClientInterfaceAppendCall wrap *gomock.Call
type MockRedisClientInterfaceAppendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceAppendCall) Return(intCmd *redis.IntCmd) *MockRedisClientInterfaceAppendCall {
	c.Call = c.Call.Return(intCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceAppendCall) Do(f func(context.Context, string, string) *redis.IntCmd) *MockRedisClientInterfaceAppendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceAppendCall) DoAndReturn(f func(context.Context, string, string) *redis.IntCmd) *MockRedisClientInterfaceAppendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BitCount mocks base method.
func (m *MockRedisClientInterface) BitCount(context1 context.Context, s string, bitCount *redis.BitCount) *redis.IntCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BitCount", context1, s, bitCount)
	intCmd, _ := ret[0].(*redis.IntCmd)
	return intCmd
}

// BitCount indicates an expected call of BitCount.
func (mr *MockRedisClientInterfaceMockRecorder) BitCount(context1, s, bitCount any) *MockRedisClientInterfaceBitCountCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BitCount", reflect.TypeOf((*MockRedisClientInterface)(nil).BitCount), context1, s, bitCount)
	return &MockRedisClientInterfaceBitCountCall{Call: call}
}

// MockRedisClientInterfaceBitCountCall wrap *gomock.Call
type MockRedisClientInterfaceBitCountCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceBitCountCall) Return(intCmd *redis.IntCmd) *MockRedisClientInterfaceBitCountCall {
	c.Call = c.Call.Return(intCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceBitCountCall) Do(f func(context.Context, string, *redis.BitCount) *redis.IntCmd) *MockRedisClientInterfaceBitCountCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceBitCountCall) DoAndReturn(f func(context.Context, string, *redis.BitCount) *redis.IntCmd) *MockRedisClientInterfaceBitCountCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Decr mocks base method.
func (m *MockRedisClientInterface) Decr(context1 context.Context, s string) *redis.IntCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decr", context1, s)
	intCmd, _ := ret[0].(*redis.IntCmd)
	return intCmd
}

// Decr indicates an expected call of Decr.
func (mr *MockRedisClientInterfaceMockRecorder) Decr(context1, s any) *MockRedisClientInterfaceDecrCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decr", reflect.TypeOf((*MockRedisClientInterface)(nil).Decr), context1, s)
	return &MockRedisClientInterfaceDecrCall{Call: call}
}

// MockRedisClientInterfaceDecrCall wrap *gomock.Call
type MockRedisClientInterfaceDecrCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceDecrCall) Return(intCmd *redis.IntCmd) *MockRedisClientInterfaceDecrCall {
	c.Call = c.Call.Return(intCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceDecrCall) Do(f func(context.Context, string) *redis.IntCmd) *MockRedisClientInterfaceDecrCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceDecrCall) DoAndReturn(f func(context.Context, string) *redis.IntCmd) *MockRedisClientInterfaceDecrCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DecrBy mocks base method.
func (m *MockRedisClientInterface) DecrBy(context1 context.Context, s string, n int64) *redis.IntCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrBy", context1, s, n)
	intCmd, _ := ret[0].(*redis.IntCmd)
	return intCmd
}

// DecrBy indicates an expected call of DecrBy.
func (mr *MockRedisClientInterfaceMockRecorder) DecrBy(context1, s, n any) *MockRedisClientInterfaceDecrByCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrBy", reflect.TypeOf((*MockRedisClientInterface)(nil).DecrBy), context1, s, n)
	return &MockRedisClientInterfaceDecrByCall{Call: call}
}

// MockRedisClientInterfaceDecrByCall wrap *gomock.Call
type MockRedisClientInterfaceDecrByCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceDecrByCall) Return(intCmd *redis.IntCmd) *MockRedisClientInterfaceDecrByCall {
	c.Call = c.Call.Return(intCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceDecrByCall) Do(f func(context.Context, string, int64) *redis.IntCmd) *MockRedisClientInterfaceDecrByCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceDecrByCall) DoAndReturn(f func(context.Context, string, int64) *redis.IntCmd) *MockRedisClientInterfaceDecrByCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Del mocks base method.
func (m *MockRedisClientInterface) Del(context1 context.Context, strings ...string) *redis.IntCmd {
	m.ctrl.T.Helper()
	varargs := []any{context1}
	for _, a := range strings {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Del", varargs...)
	intCmd, _ := ret[0].(*redis.IntCmd)
	return intCmd
}

// Del indicates an expected call of Del.
func (mr *MockRedisClientInterfaceMockRecorder) Del(context1 any,
	strings ...any) *MockRedisClientInterfaceDelCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1}, strings...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockRedisClientInterface)(nil).Del), varargs...)
	return &MockRedisClientInterfaceDelCall{Call: call}
}

// MockRedisClientInterfaceDelCall wrap *gomock.Call
type MockRedisClientInterfaceDelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceDelCall) Return(intCmd *redis.IntCmd) *MockRedisClientInterfaceDelCall {
	c.Call = c.Call.Return(intCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceDelCall) Do(f func(context.Context, ...string) *redis.IntCmd) *MockRedisClientInterfaceDelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceDelCall) DoAndReturn(f func(context.Context, ...string) *redis.IntCmd) *MockRedisClientInterfaceDelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Exists mocks base method.
func (m *MockRedisClientInterface) Exists(context1 context.Context, strings ...string) *redis.IntCmd {
	m.ctrl.T.Helper()
	varargs := []any{context1}
	for _, a := range strings {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exists", varargs...)
	intCmd, _ := ret[0].(*redis.IntCmd)
	return intCmd
}

// Exists indicates an expected call of Exists.
func (mr *MockRedisClientInterfaceMockRecorder) Exists(context1 any,
	strings ...any) *MockRedisClientInterfaceExistsCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1}, strings...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockRedisClientInterface)(nil).Exists), varargs...)
	return &MockRedisClientInterfaceExistsCall{Call: call}
}

// MockRedisClientInterfaceExistsCall wrap *gomock.Call
type MockRedisClientInterfaceExistsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceExistsCall) Return(intCmd *redis.IntCmd) *MockRedisClientInterfaceExistsCall {
	c.Call = c.Call.Return(intCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceExistsCall) Do(f func(context.Context, ...string) *redis.IntCmd) *MockRedisClientInterfaceExistsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceExistsCall) DoAndReturn(f func(context.Context, ...string) *redis.IntCmd) *MockRedisClientInterfaceExistsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Expire mocks base method.
func (m *MockRedisClientInterface) Expire(context1 context.Context, s string, duration time.Duration) *redis.BoolCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Expire", context1, s, duration)
	boolCmd, _ := ret[0].(*redis.BoolCmd)
	return boolCmd
}

// Expire indicates an expected call of Expire.
func (mr *MockRedisClientInterfaceMockRecorder) Expire(context1, s, duration any) *MockRedisClientInterfaceExpireCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Expire", reflect.TypeOf((*MockRedisClientInterface)(nil).Expire), context1, s, duration)
	return &MockRedisClientInterfaceExpireCall{Call: call}
}

// MockRedisClientInterfaceExpireCall wrap *gomock.Call
type MockRedisClientInterfaceExpireCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceExpireCall) Return(boolCmd *redis.BoolCmd) *MockRedisClientInterfaceExpireCall {
	c.Call = c.Call.Return(boolCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceExpireCall) Do(f func(context.Context, string, time.Duration) *redis.BoolCmd) *MockRedisClientInterfaceExpireCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceExpireCall) DoAndReturn(f func(context.Context, string, time.Duration) *redis.BoolCmd) *MockRedisClientInterfaceExpireCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockRedisClientInterface) Get(context1 context.Context, s string) *redis.StringCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", context1, s)
	stringCmd, _ := ret[0].(*redis.StringCmd)
	return stringCmd
}

// Get indicates an expected call of Get.
func (mr *MockRedisClientInterfaceMockRecorder) Get(context1, s any) *MockRedisClientInterfaceGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRedisClientInterface)(nil).Get), context1, s)
	return &MockRedisClientInterfaceGetCall{Call: call}
}

// MockRedisClientInterfaceGetCall wrap *gomock.Call
type MockRedisClientInterfaceGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceGetCall) Return(stringCmd *redis.StringCmd) *MockRedisClientInterfaceGetCall {
	c.Call = c.Call.Return(stringCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceGetCall) Do(f func(context.Context, string) *redis.StringCmd) *MockRedisClientInterfaceGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceGetCall) DoAndReturn(f func(context.Context, string) *redis.StringCmd) *MockRedisClientInterfaceGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetBit mocks base method.
func (m *MockRedisClientInterface) GetBit(context1 context.Context, s string, n int64) *redis.IntCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBit", context1, s, n)
	intCmd, _ := ret[0].(*redis.IntCmd)
	return intCmd
}

// GetBit indicates an expected call of GetBit.
func (mr *MockRedisClientInterfaceMockRecorder) GetBit(context1, s, n any) *MockRedisClientInterfaceGetBitCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBit", reflect.TypeOf((*MockRedisClientInterface)(nil).GetBit), context1, s, n)
	return &MockRedisClientInterfaceGetBitCall{Call: call}
}

// MockRedisClientInterfaceGetBitCall wrap *gomock.Call
type MockRedisClientInterfaceGetBitCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceGetBitCall) Return(intCmd *redis.IntCmd) *MockRedisClientInterfaceGetBitCall {
	c.Call = c.Call.Return(intCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceGetBitCall) Do(f func(context.Context, string, int64) *redis.IntCmd) *MockRedisClientInterfaceGetBitCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceGetBitCall) DoAndReturn(f func(context.Context, string, int64) *redis.IntCmd) *MockRedisClientInterfaceGetBitCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetRange mocks base method.
func (m *MockRedisClientInterface) GetRange(context1 context.Context, s string, n int64, n1 int64) *redis.StringCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRange", context1, s, n, n1)
	stringCmd, _ := ret[0].(*redis.StringCmd)
	return stringCmd
}

// GetRange indicates an expected call of GetRange.
func (mr *MockRedisClientInterfaceMockRecorder) GetRange(context1, s, n, n1 any) *MockRedisClientInterfaceGetRangeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRange", reflect.TypeOf((*MockRedisClientInterface)(nil).GetRange), context1, s, n, n1)
	return &MockRedisClientInterfaceGetRangeCall{Call: call}
}

// MockRedisClientInterfaceGetRangeCall wrap *gomock.Call
type MockRedisClientInterfaceGetRangeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceGetRangeCall) Return(stringCmd *redis.StringCmd) *MockRedisClientInterfaceGetRangeCall {
	c.Call = c.Call.Return(stringCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceGetRangeCall) Do(f func(context.Context, string, int64, int64) *redis.StringCmd) *MockRedisClientInterfaceGetRangeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceGetRangeCall) DoAndReturn(f func(context.Context, string, int64, int64) *redis.StringCmd) *MockRedisClientInterfaceGetRangeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSet mocks base method.
func (m *MockRedisClientInterface) GetSet(context1 context.Context, s string, v any) *redis.StringCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSet", context1, s, v)
	stringCmd, _ := ret[0].(*redis.StringCmd)
	return stringCmd
}

// GetSet indicates an expected call of GetSet.
func (mr *MockRedisClientInterfaceMockRecorder) GetSet(context1, s, v any) *MockRedisClientInterfaceGetSetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSet", reflect.TypeOf((*MockRedisClientInterface)(nil).GetSet), context1, s, v)
	return &MockRedisClientInterfaceGetSetCall{Call: call}
}

// MockRedisClientInterfaceGetSetCall wrap *gomock.Call
type MockRedisClientInterfaceGetSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceGetSetCall) Return(stringCmd *redis.StringCmd) *MockRedisClientInterfaceGetSetCall {
	c.Call = c.Call.Return(stringCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceGetSetCall) Do(f func(context.Context, string, any) *redis.StringCmd) *MockRedisClientInterfaceGetSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceGetSetCall) DoAndReturn(f func(context.Context, string, any) *redis.StringCmd) *MockRedisClientInterfaceGetSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Incr mocks base method.
func (m *MockRedisClientInterface) Incr(context1 context.Context, s string) *redis.IntCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Incr", context1, s)
	intCmd, _ := ret[0].(*redis.IntCmd)
	return intCmd
}

// Incr indicates an expected call of Incr.
func (mr *MockRedisClientInterfaceMockRecorder) Incr(context1, s any) *MockRedisClientInterfaceIncrCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Incr", reflect.TypeOf((*MockRedisClientInterface)(nil).Incr), context1, s)
	return &MockRedisClientInterfaceIncrCall{Call: call}
}

// MockRedisClientInterfaceIncrCall wrap *gomock.Call
type MockRedisClientInterfaceIncrCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceIncrCall) Return(intCmd *redis.IntCmd) *MockRedisClientInterfaceIncrCall {
	c.Call = c.Call.Return(intCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceIncrCall) Do(f func(context.Context, string) *redis.IntCmd) *MockRedisClientInterfaceIncrCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceIncrCall) DoAndReturn(f func(context.Context, string) *redis.IntCmd) *MockRedisClientInterfaceIncrCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IncrBy mocks base method.
func (m *MockRedisClientInterface) IncrBy(context1 context.Context, s string, n int64) *redis.IntCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrBy", context1, s, n)
	intCmd, _ := ret[0].(*redis.IntCmd)
	return intCmd
}

// IncrBy indicates an expected call of IncrBy.
func (mr *MockRedisClientInterfaceMockRecorder) IncrBy(context1, s, n any) *MockRedisClientInterfaceIncrByCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrBy", reflect.TypeOf((*MockRedisClientInterface)(nil).IncrBy), context1, s, n)
	return &MockRedisClientInterfaceIncrByCall{Call: call}
}

// MockRedisClientInterfaceIncrByCall wrap *gomock.Call
type MockRedisClientInterfaceIncrByCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceIncrByCall) Return(intCmd *redis.IntCmd) *MockRedisClientInterfaceIncrByCall {
	c.Call = c.Call.Return(intCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceIncrByCall) Do(f func(context.Context, string, int64) *redis.IntCmd) *MockRedisClientInterfaceIncrByCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceIncrByCall) DoAndReturn(f func(context.Context, string, int64) *redis.IntCmd) *MockRedisClientInterfaceIncrByCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IncrByFloat mocks base method.
func (m *MockRedisClientInterface) IncrByFloat(context1 context.Context, s string, f float64) *redis.FloatCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrByFloat", context1, s, f)
	floatCmd, _ := ret[0].(*redis.FloatCmd)
	return floatCmd
}

// IncrByFloat indicates an expected call of IncrByFloat.
func (mr *MockRedisClientInterfaceMockRecorder) IncrByFloat(context1, s, f any) *MockRedisClientInterfaceIncrByFloatCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrByFloat", reflect.TypeOf((*MockRedisClientInterface)(nil).IncrByFloat), context1, s, f)
	return &MockRedisClientInterfaceIncrByFloatCall{Call: call}
}

// MockRedisClientInterfaceIncrByFloatCall wrap *gomock.Call
type MockRedisClientInterfaceIncrByFloatCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceIncrByFloatCall) Return(floatCmd *redis.FloatCmd) *MockRedisClientInterfaceIncrByFloatCall {
	c.Call = c.Call.Return(floatCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceIncrByFloatCall) Do(f func(context.Context, string, float64) *redis.FloatCmd) *MockRedisClientInterfaceIncrByFloatCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceIncrByFloatCall) DoAndReturn(f func(context.Context, string, float64) *redis.FloatCmd) *MockRedisClientInterfaceIncrByFloatCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MGet mocks base method.
func (m *MockRedisClientInterface) MGet(context1 context.Context, strings ...string) *redis.SliceCmd {
	m.ctrl.T.Helper()
	varargs := []any{context1}
	for _, a := range strings {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MGet", varargs...)
	sliceCmd, _ := ret[0].(*redis.SliceCmd)
	return sliceCmd
}

// MGet indicates an expected call of MGet.
func (mr *MockRedisClientInterfaceMockRecorder) MGet(context1 any,
	strings ...any) *MockRedisClientInterfaceMGetCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1}, strings...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MGet", reflect.TypeOf((*MockRedisClientInterface)(nil).MGet), varargs...)
	return &MockRedisClientInterfaceMGetCall{Call: call}
}

// MockRedisClientInterfaceMGetCall wrap *gomock.Call
type MockRedisClientInterfaceMGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceMGetCall) Return(sliceCmd *redis.SliceCmd) *MockRedisClientInterfaceMGetCall {
	c.Call = c.Call.Return(sliceCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceMGetCall) Do(f func(context.Context, ...string) *redis.SliceCmd) *MockRedisClientInterfaceMGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceMGetCall) DoAndReturn(f func(context.Context, ...string) *redis.SliceCmd) *MockRedisClientInterfaceMGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MSet mocks base method.
func (m *MockRedisClientInterface) MSet(context1 context.Context, vs ...any) *redis.StatusCmd {
	m.ctrl.T.Helper()
	varargs := []any{context1}
	for _, a := range vs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MSet", varargs...)
	statusCmd, _ := ret[0].(*redis.StatusCmd)
	return statusCmd
}

// MSet indicates an expected call of MSet.
func (mr *MockRedisClientInterfaceMockRecorder) MSet(context1 any,
	vs ...any) *MockRedisClientInterfaceMSetCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1}, vs...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MSet", reflect.TypeOf((*MockRedisClientInterface)(nil).MSet), varargs...)
	return &MockRedisClientInterfaceMSetCall{Call: call}
}

// MockRedisClientInterfaceMSetCall wrap *gomock.Call
type MockRedisClientInterfaceMSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceMSetCall) Return(statusCmd *redis.StatusCmd) *MockRedisClientInterfaceMSetCall {
	c.Call = c.Call.Return(statusCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceMSetCall) Do(f func(context.Context, ...any) *redis.StatusCmd) *MockRedisClientInterfaceMSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceMSetCall) DoAndReturn(f func(context.Context, ...any) *redis.StatusCmd) *MockRedisClientInterfaceMSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MSetNX mocks base method.
func (m *MockRedisClientInterface) MSetNX(context1 context.Context, vs ...any) *redis.BoolCmd {
	m.ctrl.T.Helper()
	varargs := []any{context1}
	for _, a := range vs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MSetNX", varargs...)
	boolCmd, _ := ret[0].(*redis.BoolCmd)
	return boolCmd
}

// MSetNX indicates an expected call of MSetNX.
func (mr *MockRedisClientInterfaceMockRecorder) MSetNX(context1 any,
	vs ...any) *MockRedisClientInterfaceMSetNXCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1}, vs...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MSetNX", reflect.TypeOf((*MockRedisClientInterface)(nil).MSetNX), varargs...)
	return &MockRedisClientInterfaceMSetNXCall{Call: call}
}

// MockRedisClientInterfaceMSetNXCall wrap *gomock.Call
type MockRedisClientInterfaceMSetNXCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceMSetNXCall) Return(boolCmd *redis.BoolCmd) *MockRedisClientInterfaceMSetNXCall {
	c.Call = c.Call.Return(boolCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceMSetNXCall) Do(f func(context.Context, ...any) *redis.BoolCmd) *MockRedisClientInterfaceMSetNXCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceMSetNXCall) DoAndReturn(f func(context.Context, ...any) *redis.BoolCmd) *MockRedisClientInterfaceMSetNXCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Ping mocks base method.
func (m *MockRedisClientInterface) Ping(context1 context.Context) *redis.StatusCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", context1)
	statusCmd, _ := ret[0].(*redis.StatusCmd)
	return statusCmd
}

// Ping indicates an expected call of Ping.
func (mr *MockRedisClientInterfaceMockRecorder) Ping(context1 any) *MockRedisClientInterfacePingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRedisClientInterface)(nil).Ping), context1)
	return &MockRedisClientInterfacePingCall{Call: call}
}

// MockRedisClientInterfacePingCall wrap *gomock.Call
type MockRedisClientInterfacePingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfacePingCall) Return(statusCmd *redis.StatusCmd) *MockRedisClientInterfacePingCall {
	c.Call = c.Call.Return(statusCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfacePingCall) Do(f func(context.Context) *redis.StatusCmd) *MockRedisClientInterfacePingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfacePingCall) DoAndReturn(f func(context.Context) *redis.StatusCmd) *MockRedisClientInterfacePingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Set mocks base method.
func (m *MockRedisClientInterface) Set(context1 context.Context, s string, v any, duration time.Duration) *redis.StatusCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", context1, s, v, duration)
	statusCmd, _ := ret[0].(*redis.StatusCmd)
	return statusCmd
}

// Set indicates an expected call of Set.
func (mr *MockRedisClientInterfaceMockRecorder) Set(context1, s, v, duration any) *MockRedisClientInterfaceSetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRedisClientInterface)(nil).Set), context1, s, v, duration)
	return &MockRedisClientInterfaceSetCall{Call: call}
}

// MockRedisClientInterfaceSetCall wrap *gomock.Call
type MockRedisClientInterfaceSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceSetCall) Return(statusCmd *redis.StatusCmd) *MockRedisClientInterfaceSetCall {
	c.Call = c.Call.Return(statusCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceSetCall) Do(f func(context.Context, string, any, time.Duration) *redis.StatusCmd) *MockRedisClientInterfaceSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceSetCall) DoAndReturn(f func(context.Context, string, any, time.Duration) *redis.StatusCmd) *MockRedisClientInterfaceSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetBit mocks base method.
func (m *MockRedisClientInterface) SetBit(context1 context.Context, s string, n int64, n1 int) *redis.IntCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBit", context1, s, n, n1)
	intCmd, _ := ret[0].(*redis.IntCmd)
	return intCmd
}

// SetBit indicates an expected call of SetBit.
func (mr *MockRedisClientInterfaceMockRecorder) SetBit(context1, s, n, n1 any) *MockRedisClientInterfaceSetBitCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBit", reflect.TypeOf((*MockRedisClientInterface)(nil).SetBit), context1, s, n, n1)
	return &MockRedisClientInterfaceSetBitCall{Call: call}
}

// MockRedisClientInterfaceSetBitCall wrap *gomock.Call
type MockRedisClientInterfaceSetBitCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceSetBitCall) Return(intCmd *redis.IntCmd) *MockRedisClientInterfaceSetBitCall {
	c.Call = c.Call.Return(intCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceSetBitCall) Do(f func(context.Context, string, int64, int) *redis.IntCmd) *MockRedisClientInterfaceSetBitCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceSetBitCall) DoAndReturn(f func(context.Context, string, int64, int) *redis.IntCmd) *MockRedisClientInterfaceSetBitCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetEx mocks base method.
func (m *MockRedisClientInterface) SetEx(context1 context.Context, s string, v any, duration time.Duration) *redis.StatusCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEx", context1, s, v, duration)
	statusCmd, _ := ret[0].(*redis.StatusCmd)
	return statusCmd
}

// SetEx indicates an expected call of SetEx.
func (mr *MockRedisClientInterfaceMockRecorder) SetEx(context1, s, v, duration any) *MockRedisClientInterfaceSetExCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEx", reflect.TypeOf((*MockRedisClientInterface)(nil).SetEx), context1, s, v, duration)
	return &MockRedisClientInterfaceSetExCall{Call: call}
}

// MockRedisClientInterfaceSetExCall wrap *gomock.Call
type MockRedisClientInterfaceSetExCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceSetExCall) Return(statusCmd *redis.StatusCmd) *MockRedisClientInterfaceSetExCall {
	c.Call = c.Call.Return(statusCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceSetExCall) Do(f func(context.Context, string, any, time.Duration) *redis.StatusCmd) *MockRedisClientInterfaceSetExCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceSetExCall) DoAndReturn(f func(context.Context, string, any, time.Duration) *redis.StatusCmd) *MockRedisClientInterfaceSetExCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetNX mocks base method.
func (m *MockRedisClientInterface) SetNX(context1 context.Context, s string, v any, duration time.Duration) *redis.BoolCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNX", context1, s, v, duration)
	boolCmd, _ := ret[0].(*redis.BoolCmd)
	return boolCmd
}

// SetNX indicates an expected call of SetNX.
func (mr *MockRedisClientInterfaceMockRecorder) SetNX(context1, s, v, duration any) *MockRedisClientInterfaceSetNXCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNX", reflect.TypeOf((*MockRedisClientInterface)(nil).SetNX), context1, s, v, duration)
	return &MockRedisClientInterfaceSetNXCall{Call: call}
}

// MockRedisClientInterfaceSetNXCall wrap *gomock.Call
type MockRedisClientInterfaceSetNXCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceSetNXCall) Return(boolCmd *redis.BoolCmd) *MockRedisClientInterfaceSetNXCall {
	c.Call = c.Call.Return(boolCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceSetNXCall) Do(f func(context.Context, string, any, time.Duration) *redis.BoolCmd) *MockRedisClientInterfaceSetNXCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceSetNXCall) DoAndReturn(f func(context.Context, string, any, time.Duration) *redis.BoolCmd) *MockRedisClientInterfaceSetNXCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetRange mocks base method.
func (m *MockRedisClientInterface) SetRange(context1 context.Context, s string, n int64, s1 string) *redis.IntCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRange", context1, s, n, s1)
	intCmd, _ := ret[0].(*redis.IntCmd)
	return intCmd
}

// SetRange indicates an expected call of SetRange.
func (mr *MockRedisClientInterfaceMockRecorder) SetRange(context1, s, n, s1 any) *MockRedisClientInterfaceSetRangeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRange", reflect.TypeOf((*MockRedisClientInterface)(nil).SetRange), context1, s, n, s1)
	return &MockRedisClientInterfaceSetRangeCall{Call: call}
}

// MockRedisClientInterfaceSetRangeCall wrap *gomock.Call
type MockRedisClientInterfaceSetRangeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceSetRangeCall) Return(intCmd *redis.IntCmd) *MockRedisClientInterfaceSetRangeCall {
	c.Call = c.Call.Return(intCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceSetRangeCall) Do(f func(context.Context, string, int64, string) *redis.IntCmd) *MockRedisClientInterfaceSetRangeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceSetRangeCall) DoAndReturn(f func(context.Context, string, int64, string) *redis.IntCmd) *MockRedisClientInterfaceSetRangeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StrLen mocks base method.
func (m *MockRedisClientInterface) StrLen(context1 context.Context, s string) *redis.IntCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StrLen", context1, s)
	intCmd, _ := ret[0].(*redis.IntCmd)
	return intCmd
}

// StrLen indicates an expected call of StrLen.
func (mr *MockRedisClientInterfaceMockRecorder) StrLen(context1, s any) *MockRedisClientInterfaceStrLenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StrLen", reflect.TypeOf((*MockRedisClientInterface)(nil).StrLen), context1, s)
	return &MockRedisClientInterfaceStrLenCall{Call: call}
}

// MockRedisClientInterfaceStrLenCall wrap *gomock.Call
type MockRedisClientInterfaceStrLenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceStrLenCall) Return(intCmd *redis.IntCmd) *MockRedisClientInterfaceStrLenCall {
	c.Call = c.Call.Return(intCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceStrLenCall) Do(f func(context.Context, string) *redis.IntCmd) *MockRedisClientInterfaceStrLenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceStrLenCall) DoAndReturn(f func(context.Context, string) *redis.IntCmd) *MockRedisClientInterfaceStrLenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TTL mocks base method.
func (m *MockRedisClientInterface) TTL(context1 context.Context, s string) *redis.DurationCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TTL", context1, s)
	durationCmd, _ := ret[0].(*redis.DurationCmd)
	return durationCmd
}

// TTL indicates an expected call of TTL.
func (mr *MockRedisClientInterfaceMockRecorder) TTL(context1, s any) *MockRedisClientInterfaceTTLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TTL", reflect.TypeOf((*MockRedisClientInterface)(nil).TTL), context1, s)
	return &MockRedisClientInterfaceTTLCall{Call: call}
}

// MockRedisClientInterfaceTTLCall wrap *gomock.Call
type MockRedisClientInterfaceTTLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientInterfaceTTLCall) Return(durationCmd *redis.DurationCmd) *MockRedisClientInterfaceTTLCall {
	c.Call = c.Call.Return(durationCmd)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientInterfaceTTLCall) Do(f func(context.Context, string) *redis.DurationCmd) *MockRedisClientInterfaceTTLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientInterfaceTTLCall) DoAndReturn(f func(context.Context, string) *redis.DurationCmd) *MockRedisClientInterfaceTTLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
