// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/service/secretsmanager"
	"go.uber.org/mock/gomock"
)

// MockAWSSecretsManagerClientInterface is a mock of AWSSecretsManagerClientInterface interface.
type MockAWSSecretsManagerClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAWSSecretsManagerClientInterfaceMockRecorder
	isgomock struct{}
}

// MockAWSSecretsManagerClientInterfaceMockRecorder is the mock recorder for MockAWSSecretsManagerClientInterface.
type MockAWSSecretsManagerClientInterfaceMockRecorder struct {
	mock *MockAWSSecretsManagerClientInterface
}

// NewMockAWSSecretsManagerClientInterface creates a new mock instance.
func NewMockAWSSecretsManagerClientInterface(ctrl *gomock.Controller) *MockAWSSecretsManagerClientInterface {
	mock := &MockAWSSecretsManagerClientInterface{ctrl: ctrl}
	mock.recorder = &MockAWSSecretsManagerClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAWSSecretsManagerClientInterface) EXPECT() *MockAWSSecretsManagerClientInterfaceMockRecorder {
	return m.recorder
}

// GetSecretValue mocks base method.
func (m *MockAWSSecretsManagerClientInterface) GetSecretValue(context1 context.Context, getSecretValueInput *secretsmanager.GetSecretValueInput, fns ...func(*secretsmanager.Options)) (*secretsmanager.GetSecretValueOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, getSecretValueInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSecretValue", varargs...)
	getSecretValueOutput, _ := ret[0].(*secretsmanager.GetSecretValueOutput)
	err, _ := ret[1].(error)
	return getSecretValueOutput, err
}

// GetSecretValue indicates an expected call of GetSecretValue.
func (mr *MockAWSSecretsManagerClientInterfaceMockRecorder) GetSecretValue(context1, getSecretValueInput any,
	fns ...any) *MockAWSSecretsManagerClientInterfaceGetSecretValueCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, getSecretValueInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretValue", reflect.TypeOf((*MockAWSSecretsManagerClientInterface)(nil).GetSecretValue), varargs...)
	return &MockAWSSecretsManagerClientInterfaceGetSecretValueCall{Call: call}
}

// MockAWSSecretsManagerClientInterfaceGetSecretValueCall wrap *gomock.Call
type MockAWSSecretsManagerClientInterfaceGetSecretValueCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSSecretsManagerClientInterfaceGetSecretValueCall) Return(getSecretValueOutput *secretsmanager.GetSecretValueOutput, err error) *MockAWSSecretsManagerClientInterfaceGetSecretValueCall {
	c.Call = c.Call.Return(getSecretValueOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSSecretsManagerClientInterfaceGetSecretValueCall) Do(f func(context.Context, *secretsmanager.GetSecretValueInput, ...func(*secretsmanager.Options)) (*secretsmanager.GetSecretValueOutput, error)) *MockAWSSecretsManagerClientInterfaceGetSecretValueCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSSecretsManagerClientInterfaceGetSecretValueCall) DoAndReturn(f func(context.Context, *secretsmanager.GetSecretValueInput, ...func(*secretsmanager.Options)) (*secretsmanager.GetSecretValueOutput, error)) *MockAWSSecretsManagerClientInterfaceGetSecretValueCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
