// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/service/sesv2"
	"go.uber.org/mock/gomock"
)

// MockAWSSESClientInterface is a mock of AWSSESClientInterface interface.
type MockAWSSESClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAWSSESClientInterfaceMockRecorder
	isgomock struct{}
}

// MockAWSSESClientInterfaceMockRecorder is the mock recorder for MockAWSSESClientInterface.
type MockAWSSESClientInterfaceMockRecorder struct {
	mock *MockAWSSESClientInterface
}

// NewMockAWSSESClientInterface creates a new mock instance.
func NewMockAWSSESClientInterface(ctrl *gomock.Controller) *MockAWSSESClientInterface {
	mock := &MockAWSSESClientInterface{ctrl: ctrl}
	mock.recorder = &MockAWSSESClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAWSSESClientInterface) EXPECT() *MockAWSSESClientInterfaceMockRecorder {
	return m.recorder
}

// SendBulkEmail mocks base method.
func (m *MockAWSSESClientInterface) SendBulkEmail(context1 context.Context, sendBulkEmailInput *sesv2.SendBulkEmailInput, fns ...func(*sesv2.Options)) (*sesv2.SendBulkEmailOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, sendBulkEmailInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendBulkEmail", varargs...)
	sendBulkEmailOutput, _ := ret[0].(*sesv2.SendBulkEmailOutput)
	err, _ := ret[1].(error)
	return sendBulkEmailOutput, err
}

// SendBulkEmail indicates an expected call of SendBulkEmail.
func (mr *MockAWSSESClientInterfaceMockRecorder) SendBulkEmail(context1, sendBulkEmailInput any,
	fns ...any) *MockAWSSESClientInterfaceSendBulkEmailCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, sendBulkEmailInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBulkEmail", reflect.TypeOf((*MockAWSSESClientInterface)(nil).SendBulkEmail), varargs...)
	return &MockAWSSESClientInterfaceSendBulkEmailCall{Call: call}
}

// MockAWSSESClientInterfaceSendBulkEmailCall wrap *gomock.Call
type MockAWSSESClientInterfaceSendBulkEmailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSSESClientInterfaceSendBulkEmailCall) Return(sendBulkEmailOutput *sesv2.SendBulkEmailOutput, err error) *MockAWSSESClientInterfaceSendBulkEmailCall {
	c.Call = c.Call.Return(sendBulkEmailOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSSESClientInterfaceSendBulkEmailCall) Do(f func(context.Context, *sesv2.SendBulkEmailInput, ...func(*sesv2.Options)) (*sesv2.SendBulkEmailOutput, error)) *MockAWSSESClientInterfaceSendBulkEmailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSSESClientInterfaceSendBulkEmailCall) DoAndReturn(f func(context.Context, *sesv2.SendBulkEmailInput, ...func(*sesv2.Options)) (*sesv2.SendBulkEmailOutput, error)) *MockAWSSESClientInterfaceSendBulkEmailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SendEmail mocks base method.
func (m *MockAWSSESClientInterface) SendEmail(context1 context.Context, sendEmailInput *sesv2.SendEmailInput, fns ...func(*sesv2.Options)) (*sesv2.SendEmailOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, sendEmailInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendEmail", varargs...)
	sendEmailOutput, _ := ret[0].(*sesv2.SendEmailOutput)
	err, _ := ret[1].(error)
	return sendEmailOutput, err
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockAWSSESClientInterfaceMockRecorder) SendEmail(context1, sendEmailInput any,
	fns ...any) *MockAWSSESClientInterfaceSendEmailCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, sendEmailInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockAWSSESClientInterface)(nil).SendEmail), varargs...)
	return &MockAWSSESClientInterfaceSendEmailCall{Call: call}
}

// MockAWSSESClientInterfaceSendEmailCall wrap *gomock.Call
type MockAWSSESClientInterfaceSendEmailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSSESClientInterfaceSendEmailCall) Return(sendEmailOutput *sesv2.SendEmailOutput, err error) *MockAWSSESClientInterfaceSendEmailCall {
	c.Call = c.Call.Return(sendEmailOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSSESClientInterfaceSendEmailCall) Do(f func(context.Context, *sesv2.SendEmailInput, ...func(*sesv2.Options)) (*sesv2.SendEmailOutput, error)) *MockAWSSESClientInterfaceSendEmailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSSESClientInterfaceSendEmailCall) DoAndReturn(f func(context.Context, *sesv2.SendEmailInput, ...func(*sesv2.Options)) (*sesv2.SendEmailOutput, error)) *MockAWSSESClientInterfaceSendEmailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
