// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/feature/s3/transfermanager"
	"go.uber.org/mock/gomock"
)

// MockAWSS3TransferClientInterface is a mock of AWSS3TransferClientInterface interface.
type MockAWSS3TransferClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAWSS3TransferClientInterfaceMockRecorder
	isgomock struct{}
}

// MockAWSS3TransferClientInterfaceMockRecorder is the mock recorder for MockAWSS3TransferClientInterface.
type MockAWSS3TransferClientInterfaceMockRecorder struct {
	mock *MockAWSS3TransferClientInterface
}

// NewMockAWSS3TransferClientInterface creates a new mock instance.
func NewMockAWSS3TransferClientInterface(ctrl *gomock.Controller) *MockAWSS3TransferClientInterface {
	mock := &MockAWSS3TransferClientInterface{ctrl: ctrl}
	mock.recorder = &MockAWSS3TransferClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAWSS3TransferClientInterface) EXPECT() *MockAWSS3TransferClientInterfaceMockRecorder {
	return m.recorder
}

// DownloadObject mocks base method.
func (m *MockAWSS3TransferClientInterface) DownloadObject(context1 context.Context, downloadObjectInput *transfermanager.DownloadObjectInput, fns ...func(*transfermanager.Options)) (*transfermanager.DownloadObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, downloadObjectInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DownloadObject", varargs...)
	downloadObjectOutput, _ := ret[0].(*transfermanager.DownloadObjectOutput)
	err, _ := ret[1].(error)
	return downloadObjectOutput, err
}

// DownloadObject indicates an expected call of DownloadObject.
func (mr *MockAWSS3TransferClientInterfaceMockRecorder) DownloadObject(context1, downloadObjectInput any,
	fns ...any) *MockAWSS3TransferClientInterfaceDownloadObjectCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, downloadObjectInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadObject", reflect.TypeOf((*MockAWSS3TransferClientInterface)(nil).DownloadObject), varargs...)
	return &MockAWSS3TransferClientInterfaceDownloadObjectCall{Call: call}
}

// MockAWSS3TransferClientInterfaceDownloadObjectCall wrap *gomock.Call
type MockAWSS3TransferClientInterfaceDownloadObjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSS3TransferClientInterfaceDownloadObjectCall) Return(downloadObjectOutput *transfermanager.DownloadObjectOutput, err error) *MockAWSS3TransferClientInterfaceDownloadObjectCall {
	c.Call = c.Call.Return(downloadObjectOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSS3TransferClientInterfaceDownloadObjectCall) Do(f func(context.Context, *transfermanager.DownloadObjectInput, ...func(*transfermanager.Options)) (*transfermanager.DownloadObjectOutput, error)) *MockAWSS3TransferClientInterfaceDownloadObjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSS3TransferClientInterfaceDownloadObjectCall) DoAndReturn(f func(context.Context, *transfermanager.DownloadObjectInput, ...func(*transfermanager.Options)) (*transfermanager.DownloadObjectOutput, error)) *MockAWSS3TransferClientInterfaceDownloadObjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UploadObject mocks base method.
func (m *MockAWSS3TransferClientInterface) UploadObject(context1 context.Context, uploadObjectInput *transfermanager.UploadObjectInput, fns ...func(*transfermanager.Options)) (*transfermanager.UploadObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, uploadObjectInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UploadObject", varargs...)
	uploadObjectOutput, _ := ret[0].(*transfermanager.UploadObjectOutput)
	err, _ := ret[1].(error)
	return uploadObjectOutput, err
}

// UploadObject indicates an expected call of UploadObject.
func (mr *MockAWSS3TransferClientInterfaceMockRecorder) UploadObject(context1, uploadObjectInput any,
	fns ...any) *MockAWSS3TransferClientInterfaceUploadObjectCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, uploadObjectInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadObject", reflect.TypeOf((*MockAWSS3TransferClientInterface)(nil).UploadObject), varargs...)
	return &MockAWSS3TransferClientInterfaceUploadObjectCall{Call: call}
}

// MockAWSS3TransferClientInterfaceUploadObjectCall wrap *gomock.Call
type MockAWSS3TransferClientInterfaceUploadObjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSS3TransferClientInterfaceUploadObjectCall) Return(uploadObjectOutput *transfermanager.UploadObjectOutput, err error) *MockAWSS3TransferClientInterfaceUploadObjectCall {
	c.Call = c.Call.Return(uploadObjectOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSS3TransferClientInterfaceUploadObjectCall) Do(f func(context.Context, *transfermanager.UploadObjectInput, ...func(*transfermanager.Options)) (*transfermanager.UploadObjectOutput, error)) *MockAWSS3TransferClientInterfaceUploadObjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSS3TransferClientInterfaceUploadObjectCall) DoAndReturn(f func(context.Context, *transfermanager.UploadObjectInput, ...func(*transfermanager.Options)) (*transfermanager.UploadObjectOutput, error)) *MockAWSS3TransferClientInterfaceUploadObjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
