// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"reflect"

	"github.com/slack-go/slack"
	"go.uber.org/mock/gomock"
)

// MockSlackClientInterface is a mock of SlackClientInterface interface.
type MockSlackClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSlackClientInterfaceMockRecorder
	isgomock struct{}
}

// MockSlackClientInterfaceMockRecorder is the mock recorder for MockSlackClientInterface.
type MockSlackClientInterfaceMockRecorder struct {
	mock *MockSlackClientInterface
}

// NewMockSlackClientInterface creates a new mock instance.
func NewMockSlackClientInterface(ctrl *gomock.Controller) *MockSlackClientInterface {
	mock := &MockSlackClientInterface{ctrl: ctrl}
	mock.recorder = &MockSlackClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlackClientInterface) EXPECT() *MockSlackClientInterfaceMockRecorder {
	return m.recorder
}

// PostMessage mocks base method.
func (m *MockSlackClientInterface) PostMessage(s string, msgOptions ...slack.MsgOption) (string, string, error) {
	m.ctrl.T.Helper()
	varargs := []any{s}
	for _, a := range msgOptions {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostMessage", varargs...)
	s1, _ := ret[0].(string)
	s2, _ := ret[1].(string)
	err, _ := ret[2].(error)
	return s1, s2, err
}

// PostMessage indicates an expected call of PostMessage.
func (mr *MockSlackClientInterfaceMockRecorder) PostMessage(s any,
	msgOptions ...any) *MockSlackClientInterfacePostMessageCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{s}, msgOptions...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostMessage", reflect.TypeOf((*MockSlackClientInterface)(nil).PostMessage), varargs...)
	return &MockSlackClientInterfacePostMessageCall{Call: call}
}

// MockSlackClientInterfacePostMessageCall wrap *gomock.Call
type MockSlackClientInterfacePostMessageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSlackClientInterfacePostMessageCall) Return(s1 string, s2 string, err error) *MockSlackClientInterfacePostMessageCall {
	c.Call = c.Call.Return(s1, s2, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSlackClientInterfacePostMessageCall) Do(f func(string, ...slack.MsgOption) (string, string, error)) *MockSlackClientInterfacePostMessageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSlackClientInterfacePostMessageCall) DoAndReturn(f func(string, ...slack.MsgOption) (string, string, error)) *MockSlackClientInterfacePostMessageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
