// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/service/bedrockruntime"
	"go.uber.org/mock/gomock"
)

// MockAWSBedrockClientInterface is a mock of AWSBedrockClientInterface interface.
type MockAWSBedrockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAWSBedrockClientInterfaceMockRecorder
	isgomock struct{}
}

// MockAWSBedrockClientInterfaceMockRecorder is the mock recorder for MockAWSBedrockClientInterface.
type MockAWSBedrockClientInterfaceMockRecorder struct {
	mock *MockAWSBedrockClientInterface
}

// NewMockAWSBedrockClientInterface creates a new mock instance.
func NewMockAWSBedrockClientInterface(ctrl *gomock.Controller) *MockAWSBedrockClientInterface {
	mock := &MockAWSBedrockClientInterface{ctrl: ctrl}
	mock.recorder = &MockAWSBedrockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAWSBedrockClientInterface) EXPECT() *MockAWSBedrockClientInterfaceMockRecorder {
	return m.recorder
}

// Converse mocks base method.
func (m *MockAWSBedrockClientInterface) Converse(context1 context.Context, converseInput *bedrockruntime.ConverseInput, fns ...func(*bedrockruntime.Options)) (*bedrockruntime.ConverseOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, converseInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Converse", varargs...)
	converseOutput, _ := ret[0].(*bedrockruntime.ConverseOutput)
	err, _ := ret[1].(error)
	return converseOutput, err
}

// Converse indicates an expected call of Converse.
func (mr *MockAWSBedrockClientInterfaceMockRecorder) Converse(context1, converseInput any,
	fns ...any) *MockAWSBedrockClientInterfaceConverseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, converseInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Converse", reflect.TypeOf((*MockAWSBedrockClientInterface)(nil).Converse), varargs...)
	return &MockAWSBedrockClientInterfaceConverseCall{Call: call}
}

// MockAWSBedrockClientInterfaceConverseCall wrap *gomock.Call
type MockAWSBedrockClientInterfaceConverseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSBedrockClientInterfaceConverseCall) Return(converseOutput *bedrockruntime.ConverseOutput, err error) *MockAWSBedrockClientInterfaceConverseCall {
	c.Call = c.Call.Return(converseOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSBedrockClientInterfaceConverseCall) Do(f func(context.Context, *bedrockruntime.ConverseInput, ...func(*bedrockruntime.Options)) (*bedrockruntime.ConverseOutput, error)) *MockAWSBedrockClientInterfaceConverseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSBedrockClientInterfaceConverseCall) DoAndReturn(f func(context.Context, *bedrockruntime.ConverseInput, ...func(*bedrockruntime.Options)) (*bedrockruntime.ConverseOutput, error)) *MockAWSBedrockClientInterfaceConverseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// InvokeModel mocks base method.
func (m *MockAWSBedrockClientInterface) InvokeModel(context1 context.Context, invokeModelInput *bedrockruntime.InvokeModelInput, fns ...func(*bedrockruntime.Options)) (*bedrockruntime.InvokeModelOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, invokeModelInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InvokeModel", varargs...)
	invokeModelOutput, _ := ret[0].(*bedrockruntime.InvokeModelOutput)
	err, _ := ret[1].(error)
	return invokeModelOutput, err
}

// InvokeModel indicates an expected call of InvokeModel.
func (mr *MockAWSBedrockClientInterfaceMockRecorder) InvokeModel(context1, invokeModelInput any,
	fns ...any) *MockAWSBedrockClientInterfaceInvokeModelCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, invokeModelInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvokeModel", reflect.TypeOf((*MockAWSBedrockClientInterface)(nil).InvokeModel), varargs...)
	return &MockAWSBedrockClientInterfaceInvokeModelCall{Call: call}
}

// MockAWSBedrockClientInterfaceInvokeModelCall wrap *gomock.Call
type MockAWSBedrockClientInterfaceInvokeModelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSBedrockClientInterfaceInvokeModelCall) Return(invokeModelOutput *bedrockruntime.InvokeModelOutput, err error) *MockAWSBedrockClientInterfaceInvokeModelCall {
	c.Call = c.Call.Return(invokeModelOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSBedrockClientInterfaceInvokeModelCall) Do(f func(context.Context, *bedrockruntime.InvokeModelInput, ...func(*bedrockruntime.Options)) (*bedrockruntime.InvokeModelOutput, error)) *MockAWSBedrockClientInterfaceInvokeModelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSBedrockClientInterfaceInvokeModelCall) DoAndReturn(f func(context.Context, *bedrockruntime.InvokeModelInput, ...func(*bedrockruntime.Options)) (*bedrockruntime.InvokeModelOutput, error)) *MockAWSBedrockClientInterfaceInvokeModelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// InvokeModelWithResponseStream mocks base method.
func (m *MockAWSBedrockClientInterface) InvokeModelWithResponseStream(context1 context.Context, invokeModelWithResponseStreamInput *bedrockruntime.InvokeModelWithResponseStreamInput, fns ...func(*bedrockruntime.Options)) (*bedrockruntime.InvokeModelWithResponseStreamOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, invokeModelWithResponseStreamInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InvokeModelWithResponseStream", varargs...)
	invokeModelWithResponseStreamOutput, _ := ret[0].(*bedrockruntime.InvokeModelWithResponseStreamOutput)
	err, _ := ret[1].(error)
	return invokeModelWithResponseStreamOutput, err
}

// InvokeModelWithResponseStream indicates an expected call of InvokeModelWithResponseStream.
func (mr *MockAWSBedrockClientInterfaceMockRecorder) InvokeModelWithResponseStream(context1, invokeModelWithResponseStreamInput any,
	fns ...any) *MockAWSBedrockClientInterfaceInvokeModelWithResponseStreamCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, invokeModelWithResponseStreamInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvokeModelWithResponseStream", reflect.TypeOf((*MockAWSBedrockClientInterface)(nil).InvokeModelWithResponseStream), varargs...)
	return &MockAWSBedrockClientInterfaceInvokeModelWithResponseStreamCall{Call: call}
}

// MockAWSBedrockClientInterfaceInvokeModelWithResponseStreamCall wrap *gomock.Call
type MockAWSBedrockClientInterfaceInvokeModelWithResponseStreamCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSBedrockClientInterfaceInvokeModelWithResponseStreamCall) Return(invokeModelWithResponseStreamOutput *bedrockruntime.InvokeModelWithResponseStreamOutput, err error) *MockAWSBedrockClientInterfaceInvokeModelWithResponseStreamCall {
	c.Call = c.Call.Return(invokeModelWithResponseStreamOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSBedrockClientInterfaceInvokeModelWithResponseStreamCall) Do(f func(context.Context, *bedrockruntime.InvokeModelWithResponseStreamInput, ...func(*bedrockruntime.Options)) (*bedrockruntime.InvokeModelWithResponseStreamOutput, error)) *MockAWSBedrockClientInterfaceInvokeModelWithResponseStreamCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSBedrockClientInterfaceInvokeModelWithResponseStreamCall) DoAndReturn(f func(context.Context, *bedrockruntime.InvokeModelWithResponseStreamInput, ...func(*bedrockruntime.Options)) (*bedrockruntime.InvokeModelWithResponseStreamOutput, error)) *MockAWSBedrockClientInterfaceInvokeModelWithResponseStreamCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
