// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/feature/s3/manager"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"go.uber.org/mock/gomock"
)

// MockAWSS3UploaderClientInterface is a mock of AWSS3UploaderClientInterface interface.
type MockAWSS3UploaderClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAWSS3UploaderClientInterfaceMockRecorder
	isgomock struct{}
}

// MockAWSS3UploaderClientInterfaceMockRecorder is the mock recorder for MockAWSS3UploaderClientInterface.
type MockAWSS3UploaderClientInterfaceMockRecorder struct {
	mock *MockAWSS3UploaderClientInterface
}

// NewMockAWSS3UploaderClientInterface creates a new mock instance.
func NewMockAWSS3UploaderClientInterface(ctrl *gomock.Controller) *MockAWSS3UploaderClientInterface {
	mock := &MockAWSS3UploaderClientInterface{ctrl: ctrl}
	mock.recorder = &MockAWSS3UploaderClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAWSS3UploaderClientInterface) EXPECT() *MockAWSS3UploaderClientInterfaceMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockAWSS3UploaderClientInterface) Upload(context1 context.Context, putObjectInput *s3.PutObjectInput, fns ...func(*manager.Uploader)) (*manager.UploadOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, putObjectInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Upload", varargs...)
	uploadOutput, _ := ret[0].(*manager.UploadOutput)
	err, _ := ret[1].(error)
	return uploadOutput, err
}

// Upload indicates an expected call of Upload.
func (mr *MockAWSS3UploaderClientInterfaceMockRecorder) Upload(context1, putObjectInput any,
	fns ...any) *MockAWSS3UploaderClientInterfaceUploadCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, putObjectInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockAWSS3UploaderClientInterface)(nil).Upload), varargs...)
	return &MockAWSS3UploaderClientInterfaceUploadCall{Call: call}
}

// MockAWSS3UploaderClientInterfaceUploadCall wrap *gomock.Call
type MockAWSS3UploaderClientInterfaceUploadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSS3UploaderClientInterfaceUploadCall) Return(uploadOutput *manager.UploadOutput, err error) *MockAWSS3UploaderClientInterfaceUploadCall {
	c.Call = c.Call.Return(uploadOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSS3UploaderClientInterfaceUploadCall) Do(f func(context.Context, *s3.PutObjectInput, ...func(*manager.Uploader)) (*manager.UploadOutput, error)) *MockAWSS3UploaderClientInterfaceUploadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSS3UploaderClientInterfaceUploadCall) DoAndReturn(f func(context.Context, *s3.PutObjectInput, ...func(*manager.Uploader)) (*manager.UploadOutput, error)) *MockAWSS3UploaderClientInterfaceUploadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
