// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/aws/signer/v4"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"go.uber.org/mock/gomock"
)

// MockAWSS3PresignClientInterface is a mock of AWSS3PresignClientInterface interface.
type MockAWSS3PresignClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAWSS3PresignClientInterfaceMockRecorder
	isgomock struct{}
}

// MockAWSS3PresignClientInterfaceMockRecorder is the mock recorder for MockAWSS3PresignClientInterface.
type MockAWSS3PresignClientInterfaceMockRecorder struct {
	mock *MockAWSS3PresignClientInterface
}

// NewMockAWSS3PresignClientInterface creates a new mock instance.
func NewMockAWSS3PresignClientInterface(ctrl *gomock.Controller) *MockAWSS3PresignClientInterface {
	mock := &MockAWSS3PresignClientInterface{ctrl: ctrl}
	mock.recorder = &MockAWSS3PresignClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAWSS3PresignClientInterface) EXPECT() *MockAWSS3PresignClientInterfaceMockRecorder {
	return m.recorder
}

// PresignGetObject mocks base method.
func (m *MockAWSS3PresignClientInterface) PresignGetObject(context1 context.Context, getObjectInput *s3.GetObjectInput, fns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, getObjectInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PresignGetObject", varargs...)
	presignedHTTPRequest, _ := ret[0].(*v4.PresignedHTTPRequest)
	err, _ := ret[1].(error)
	return presignedHTTPRequest, err
}

// PresignGetObject indicates an expected call of PresignGetObject.
func (mr *MockAWSS3PresignClientInterfaceMockRecorder) PresignGetObject(context1, getObjectInput any,
	fns ...any) *MockAWSS3PresignClientInterfacePresignGetObjectCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, getObjectInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignGetObject", reflect.TypeOf((*MockAWSS3PresignClientInterface)(nil).PresignGetObject), varargs...)
	return &MockAWSS3PresignClientInterfacePresignGetObjectCall{Call: call}
}

// MockAWSS3PresignClientInterfacePresignGetObjectCall wrap *gomock.Call
type MockAWSS3PresignClientInterfacePresignGetObjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSS3PresignClientInterfacePresignGetObjectCall) Return(presignedHTTPRequest *v4.PresignedHTTPRequest, err error) *MockAWSS3PresignClientInterfacePresignGetObjectCall {
	c.Call = c.Call.Return(presignedHTTPRequest, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSS3PresignClientInterfacePresignGetObjectCall) Do(f func(context.Context, *s3.GetObjectInput, ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error)) *MockAWSS3PresignClientInterfacePresignGetObjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSS3PresignClientInterfacePresignGetObjectCall) DoAndReturn(f func(context.Context, *s3.GetObjectInput, ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error)) *MockAWSS3PresignClientInterfacePresignGetObjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
