// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider"
	"go.uber.org/mock/gomock"
)

// MockAWSCognitoIdentityProviderClientInterface is a mock of AWSCognitoIdentityProviderClientInterface interface.
type MockAWSCognitoIdentityProviderClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAWSCognitoIdentityProviderClientInterfaceMockRecorder
	isgomock struct{}
}

// MockAWSCognitoIdentityProviderClientInterfaceMockRecorder is the mock recorder for MockAWSCognitoIdentityProviderClientInterface.
type MockAWSCognitoIdentityProviderClientInterfaceMockRecorder struct {
	mock *MockAWSCognitoIdentityProviderClientInterface
}

// NewMockAWSCognitoIdentityProviderClientInterface creates a new mock instance.
func NewMockAWSCognitoIdentityProviderClientInterface(ctrl *gomock.Controller) *MockAWSCognitoIdentityProviderClientInterface {
	mock := &MockAWSCognitoIdentityProviderClientInterface{ctrl: ctrl}
	mock.recorder = &MockAWSCognitoIdentityProviderClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAWSCognitoIdentityProviderClientInterface) EXPECT() *MockAWSCognitoIdentityProviderClientInterfaceMockRecorder {
	return m.recorder
}

// AdminCreateUser mocks base method.
func (m *MockAWSCognitoIdentityProviderClientInterface) AdminCreateUser(context1 context.Context, adminCreateUserInput *cognitoidentityprovider.AdminCreateUserInput, fns ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.AdminCreateUserOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, adminCreateUserInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminCreateUser", varargs...)
	adminCreateUserOutput, _ := ret[0].(*cognitoidentityprovider.AdminCreateUserOutput)
	err, _ := ret[1].(error)
	return adminCreateUserOutput, err
}

// AdminCreateUser indicates an expected call of AdminCreateUser.
func (mr *MockAWSCognitoIdentityProviderClientInterfaceMockRecorder) AdminCreateUser(context1, adminCreateUserInput any,
	fns ...any) *MockAWSCognitoIdentityProviderClientInterfaceAdminCreateUserCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, adminCreateUserInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminCreateUser", reflect.TypeOf((*MockAWSCognitoIdentityProviderClientInterface)(nil).AdminCreateUser), varargs...)
	return &MockAWSCognitoIdentityProviderClientInterfaceAdminCreateUserCall{Call: call}
}

// MockAWSCognitoIdentityProviderClientInterfaceAdminCreateUserCall wrap *gomock.Call
type MockAWSCognitoIdentityProviderClientInterfaceAdminCreateUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSCognitoIdentityProviderClientInterfaceAdminCreateUserCall) Return(adminCreateUserOutput *cognitoidentityprovider.AdminCreateUserOutput, err error) *MockAWSCognitoIdentityProviderClientInterfaceAdminCreateUserCall {
	c.Call = c.Call.Return(adminCreateUserOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSCognitoIdentityProviderClientInterfaceAdminCreateUserCall) Do(f func(context.Context, *cognitoidentityprovider.AdminCreateUserInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.AdminCreateUserOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceAdminCreateUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSCognitoIdentityProviderClientInterfaceAdminCreateUserCall) DoAndReturn(f func(context.Context, *cognitoidentityprovider.AdminCreateUserInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.AdminCreateUserOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceAdminCreateUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AdminDeleteUser mocks base method.
func (m *MockAWSCognitoIdentityProviderClientInterface) AdminDeleteUser(context1 context.Context, adminDeleteUserInput *cognitoidentityprovider.AdminDeleteUserInput, fns ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.AdminDeleteUserOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, adminDeleteUserInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminDeleteUser", varargs...)
	adminDeleteUserOutput, _ := ret[0].(*cognitoidentityprovider.AdminDeleteUserOutput)
	err, _ := ret[1].(error)
	return adminDeleteUserOutput, err
}

// AdminDeleteUser indicates an expected call of AdminDeleteUser.
func (mr *MockAWSCognitoIdentityProviderClientInterfaceMockRecorder) AdminDeleteUser(context1, adminDeleteUserInput any,
	fns ...any) *MockAWSCognitoIdentityProviderClientInterfaceAdminDeleteUserCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, adminDeleteUserInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminDeleteUser", reflect.TypeOf((*MockAWSCognitoIdentityProviderClientInterface)(nil).AdminDeleteUser), varargs...)
	return &MockAWSCognitoIdentityProviderClientInterfaceAdminDeleteUserCall{Call: call}
}

// MockAWSCognitoIdentityProviderClientInterfaceAdminDeleteUserCall wrap *gomock.Call
type MockAWSCognitoIdentityProviderClientInterfaceAdminDeleteUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSCognitoIdentityProviderClientInterfaceAdminDeleteUserCall) Return(adminDeleteUserOutput *cognitoidentityprovider.AdminDeleteUserOutput, err error) *MockAWSCognitoIdentityProviderClientInterfaceAdminDeleteUserCall {
	c.Call = c.Call.Return(adminDeleteUserOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSCognitoIdentityProviderClientInterfaceAdminDeleteUserCall) Do(f func(context.Context, *cognitoidentityprovider.AdminDeleteUserInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.AdminDeleteUserOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceAdminDeleteUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSCognitoIdentityProviderClientInterfaceAdminDeleteUserCall) DoAndReturn(f func(context.Context, *cognitoidentityprovider.AdminDeleteUserInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.AdminDeleteUserOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceAdminDeleteUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AdminGetUser mocks base method.
func (m *MockAWSCognitoIdentityProviderClientInterface) AdminGetUser(context1 context.Context, adminGetUserInput *cognitoidentityprovider.AdminGetUserInput, fns ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.AdminGetUserOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, adminGetUserInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminGetUser", varargs...)
	adminGetUserOutput, _ := ret[0].(*cognitoidentityprovider.AdminGetUserOutput)
	err, _ := ret[1].(error)
	return adminGetUserOutput, err
}

// AdminGetUser indicates an expected call of AdminGetUser.
func (mr *MockAWSCognitoIdentityProviderClientInterfaceMockRecorder) AdminGetUser(context1, adminGetUserInput any,
	fns ...any) *MockAWSCognitoIdentityProviderClientInterfaceAdminGetUserCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, adminGetUserInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGetUser", reflect.TypeOf((*MockAWSCognitoIdentityProviderClientInterface)(nil).AdminGetUser), varargs...)
	return &MockAWSCognitoIdentityProviderClientInterfaceAdminGetUserCall{Call: call}
}

// MockAWSCognitoIdentityProviderClientInterfaceAdminGetUserCall wrap *gomock.Call
type MockAWSCognitoIdentityProviderClientInterfaceAdminGetUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSCognitoIdentityProviderClientInterfaceAdminGetUserCall) Return(adminGetUserOutput *cognitoidentityprovider.AdminGetUserOutput, err error) *MockAWSCognitoIdentityProviderClientInterfaceAdminGetUserCall {
	c.Call = c.Call.Return(adminGetUserOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSCognitoIdentityProviderClientInterfaceAdminGetUserCall) Do(f func(context.Context, *cognitoidentityprovider.AdminGetUserInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.AdminGetUserOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceAdminGetUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSCognitoIdentityProviderClientInterfaceAdminGetUserCall) DoAndReturn(f func(context.Context, *cognitoidentityprovider.AdminGetUserInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.AdminGetUserOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceAdminGetUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AdminInitiateAuth mocks base method.
func (m *MockAWSCognitoIdentityProviderClientInterface) AdminInitiateAuth(context1 context.Context, adminInitiateAuthInput *cognitoidentityprovider.AdminInitiateAuthInput, fns ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.AdminInitiateAuthOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, adminInitiateAuthInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminInitiateAuth", varargs...)
	adminInitiateAuthOutput, _ := ret[0].(*cognitoidentityprovider.AdminInitiateAuthOutput)
	err, _ := ret[1].(error)
	return adminInitiateAuthOutput, err
}

// AdminInitiateAuth indicates an expected call of AdminInitiateAuth.
func (mr *MockAWSCognitoIdentityProviderClientInterfaceMockRecorder) AdminInitiateAuth(context1, adminInitiateAuthInput any,
	fns ...any) *MockAWSCognitoIdentityProviderClientInterfaceAdminInitiateAuthCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, adminInitiateAuthInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminInitiateAuth", reflect.TypeOf((*MockAWSCognitoIdentityProviderClientInterface)(nil).AdminInitiateAuth), varargs...)
	return &MockAWSCognitoIdentityProviderClientInterfaceAdminInitiateAuthCall{Call: call}
}

// MockAWSCognitoIdentityProviderClientInterfaceAdminInitiateAuthCall wrap *gomock.Call
type MockAWSCognitoIdentityProviderClientInterfaceAdminInitiateAuthCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSCognitoIdentityProviderClientInterfaceAdminInitiateAuthCall) Return(adminInitiateAuthOutput *cognitoidentityprovider.AdminInitiateAuthOutput, err error) *MockAWSCognitoIdentityProviderClientInterfaceAdminInitiateAuthCall {
	c.Call = c.Call.Return(adminInitiateAuthOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSCognitoIdentityProviderClientInterfaceAdminInitiateAuthCall) Do(f func(context.Context, *cognitoidentityprovider.AdminInitiateAuthInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.AdminInitiateAuthOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceAdminInitiateAuthCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSCognitoIdentityProviderClientInterfaceAdminInitiateAuthCall) DoAndReturn(f func(context.Context, *cognitoidentityprovider.AdminInitiateAuthInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.AdminInitiateAuthOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceAdminInitiateAuthCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AdminResetUserPassword mocks base method.
func (m *MockAWSCognitoIdentityProviderClientInterface) AdminResetUserPassword(context1 context.Context, adminResetUserPasswordInput *cognitoidentityprovider.AdminResetUserPasswordInput, fns ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.AdminResetUserPasswordOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, adminResetUserPasswordInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminResetUserPassword", varargs...)
	adminResetUserPasswordOutput, _ := ret[0].(*cognitoidentityprovider.AdminResetUserPasswordOutput)
	err, _ := ret[1].(error)
	return adminResetUserPasswordOutput, err
}

// AdminResetUserPassword indicates an expected call of AdminResetUserPassword.
func (mr *MockAWSCognitoIdentityProviderClientInterfaceMockRecorder) AdminResetUserPassword(context1, adminResetUserPasswordInput any,
	fns ...any) *MockAWSCognitoIdentityProviderClientInterfaceAdminResetUserPasswordCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, adminResetUserPasswordInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminResetUserPassword", reflect.TypeOf((*MockAWSCognitoIdentityProviderClientInterface)(nil).AdminResetUserPassword), varargs...)
	return &MockAWSCognitoIdentityProviderClientInterfaceAdminResetUserPasswordCall{Call: call}
}

// MockAWSCognitoIdentityProviderClientInterfaceAdminResetUserPasswordCall wrap *gomock.Call
type MockAWSCognitoIdentityProviderClientInterfaceAdminResetUserPasswordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSCognitoIdentityProviderClientInterfaceAdminResetUserPasswordCall) Return(adminResetUserPasswordOutput *cognitoidentityprovider.AdminResetUserPasswordOutput, err error) *MockAWSCognitoIdentityProviderClientInterfaceAdminResetUserPasswordCall {
	c.Call = c.Call.Return(adminResetUserPasswordOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSCognitoIdentityProviderClientInterfaceAdminResetUserPasswordCall) Do(f func(context.Context, *cognitoidentityprovider.AdminResetUserPasswordInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.AdminResetUserPasswordOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceAdminResetUserPasswordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSCognitoIdentityProviderClientInterfaceAdminResetUserPasswordCall) DoAndReturn(f func(context.Context, *cognitoidentityprovider.AdminResetUserPasswordInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.AdminResetUserPasswordOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceAdminResetUserPasswordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AdminSetUserPassword mocks base method.
func (m *MockAWSCognitoIdentityProviderClientInterface) AdminSetUserPassword(context1 context.Context, adminSetUserPasswordInput *cognitoidentityprovider.AdminSetUserPasswordInput, fns ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.AdminSetUserPasswordOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, adminSetUserPasswordInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminSetUserPassword", varargs...)
	adminSetUserPasswordOutput, _ := ret[0].(*cognitoidentityprovider.AdminSetUserPasswordOutput)
	err, _ := ret[1].(error)
	return adminSetUserPasswordOutput, err
}

// AdminSetUserPassword indicates an expected call of AdminSetUserPassword.
func (mr *MockAWSCognitoIdentityProviderClientInterfaceMockRecorder) AdminSetUserPassword(context1, adminSetUserPasswordInput any,
	fns ...any) *MockAWSCognitoIdentityProviderClientInterfaceAdminSetUserPasswordCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, adminSetUserPasswordInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminSetUserPassword", reflect.TypeOf((*MockAWSCognitoIdentityProviderClientInterface)(nil).AdminSetUserPassword), varargs...)
	return &MockAWSCognitoIdentityProviderClientInterfaceAdminSetUserPasswordCall{Call: call}
}

// MockAWSCognitoIdentityProviderClientInterfaceAdminSetUserPasswordCall wrap *gomock.Call
type MockAWSCognitoIdentityProviderClientInterfaceAdminSetUserPasswordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSCognitoIdentityProviderClientInterfaceAdminSetUserPasswordCall) Return(adminSetUserPasswordOutput *cognitoidentityprovider.AdminSetUserPasswordOutput, err error) *MockAWSCognitoIdentityProviderClientInterfaceAdminSetUserPasswordCall {
	c.Call = c.Call.Return(adminSetUserPasswordOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSCognitoIdentityProviderClientInterfaceAdminSetUserPasswordCall) Do(f func(context.Context, *cognitoidentityprovider.AdminSetUserPasswordInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.AdminSetUserPasswordOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceAdminSetUserPasswordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSCognitoIdentityProviderClientInterfaceAdminSetUserPasswordCall) DoAndReturn(f func(context.Context, *cognitoidentityprovider.AdminSetUserPasswordInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.AdminSetUserPasswordOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceAdminSetUserPasswordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ChangePassword mocks base method.
func (m *MockAWSCognitoIdentityProviderClientInterface) ChangePassword(context1 context.Context, changePasswordInput *cognitoidentityprovider.ChangePasswordInput, fns ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.ChangePasswordOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, changePasswordInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ChangePassword", varargs...)
	changePasswordOutput, _ := ret[0].(*cognitoidentityprovider.ChangePasswordOutput)
	err, _ := ret[1].(error)
	return changePasswordOutput, err
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockAWSCognitoIdentityProviderClientInterfaceMockRecorder) ChangePassword(context1, changePasswordInput any,
	fns ...any) *MockAWSCognitoIdentityProviderClientInterfaceChangePasswordCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, changePasswordInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockAWSCognitoIdentityProviderClientInterface)(nil).ChangePassword), varargs...)
	return &MockAWSCognitoIdentityProviderClientInterfaceChangePasswordCall{Call: call}
}

// MockAWSCognitoIdentityProviderClientInterfaceChangePasswordCall wrap *gomock.Call
type MockAWSCognitoIdentityProviderClientInterfaceChangePasswordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSCognitoIdentityProviderClientInterfaceChangePasswordCall) Return(changePasswordOutput *cognitoidentityprovider.ChangePasswordOutput, err error) *MockAWSCognitoIdentityProviderClientInterfaceChangePasswordCall {
	c.Call = c.Call.Return(changePasswordOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSCognitoIdentityProviderClientInterfaceChangePasswordCall) Do(f func(context.Context, *cognitoidentityprovider.ChangePasswordInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.ChangePasswordOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceChangePasswordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSCognitoIdentityProviderClientInterfaceChangePasswordCall) DoAndReturn(f func(context.Context, *cognitoidentityprovider.ChangePasswordInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.ChangePasswordOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceChangePasswordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ConfirmForgotPassword mocks base method.
func (m *MockAWSCognitoIdentityProviderClientInterface) ConfirmForgotPassword(context1 context.Context, confirmForgotPasswordInput *cognitoidentityprovider.ConfirmForgotPasswordInput, fns ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.ConfirmForgotPasswordOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, confirmForgotPasswordInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ConfirmForgotPassword", varargs...)
	confirmForgotPasswordOutput, _ := ret[0].(*cognitoidentityprovider.ConfirmForgotPasswordOutput)
	err, _ := ret[1].(error)
	return confirmForgotPasswordOutput, err
}

// ConfirmForgotPassword indicates an expected call of ConfirmForgotPassword.
func (mr *MockAWSCognitoIdentityProviderClientInterfaceMockRecorder) ConfirmForgotPassword(context1, confirmForgotPasswordInput any,
	fns ...any) *MockAWSCognitoIdentityProviderClientInterfaceConfirmForgotPasswordCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, confirmForgotPasswordInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmForgotPassword", reflect.TypeOf((*MockAWSCognitoIdentityProviderClientInterface)(nil).ConfirmForgotPassword), varargs...)
	return &MockAWSCognitoIdentityProviderClientInterfaceConfirmForgotPasswordCall{Call: call}
}

// MockAWSCognitoIdentityProviderClientInterfaceConfirmForgotPasswordCall wrap *gomock.Call
type MockAWSCognitoIdentityProviderClientInterfaceConfirmForgotPasswordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSCognitoIdentityProviderClientInterfaceConfirmForgotPasswordCall) Return(confirmForgotPasswordOutput *cognitoidentityprovider.ConfirmForgotPasswordOutput, err error) *MockAWSCognitoIdentityProviderClientInterfaceConfirmForgotPasswordCall {
	c.Call = c.Call.Return(confirmForgotPasswordOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSCognitoIdentityProviderClientInterfaceConfirmForgotPasswordCall) Do(f func(context.Context, *cognitoidentityprovider.ConfirmForgotPasswordInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.ConfirmForgotPasswordOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceConfirmForgotPasswordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSCognitoIdentityProviderClientInterfaceConfirmForgotPasswordCall) DoAndReturn(f func(context.Context, *cognitoidentityprovider.ConfirmForgotPasswordInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.ConfirmForgotPasswordOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceConfirmForgotPasswordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ForgotPassword mocks base method.
func (m *MockAWSCognitoIdentityProviderClientInterface) ForgotPassword(context1 context.Context, forgotPasswordInput *cognitoidentityprovider.ForgotPasswordInput, fns ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.ForgotPasswordOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, forgotPasswordInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ForgotPassword", varargs...)
	forgotPasswordOutput, _ := ret[0].(*cognitoidentityprovider.ForgotPasswordOutput)
	err, _ := ret[1].(error)
	return forgotPasswordOutput, err
}

// ForgotPassword indicates an expected call of ForgotPassword.
func (mr *MockAWSCognitoIdentityProviderClientInterfaceMockRecorder) ForgotPassword(context1, forgotPasswordInput any,
	fns ...any) *MockAWSCognitoIdentityProviderClientInterfaceForgotPasswordCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, forgotPasswordInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForgotPassword", reflect.TypeOf((*MockAWSCognitoIdentityProviderClientInterface)(nil).ForgotPassword), varargs...)
	return &MockAWSCognitoIdentityProviderClientInterfaceForgotPasswordCall{Call: call}
}

// MockAWSCognitoIdentityProviderClientInterfaceForgotPasswordCall wrap *gomock.Call
type MockAWSCognitoIdentityProviderClientInterfaceForgotPasswordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSCognitoIdentityProviderClientInterfaceForgotPasswordCall) Return(forgotPasswordOutput *cognitoidentityprovider.ForgotPasswordOutput, err error) *MockAWSCognitoIdentityProviderClientInterfaceForgotPasswordCall {
	c.Call = c.Call.Return(forgotPasswordOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSCognitoIdentityProviderClientInterfaceForgotPasswordCall) Do(f func(context.Context, *cognitoidentityprovider.ForgotPasswordInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.ForgotPasswordOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceForgotPasswordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSCognitoIdentityProviderClientInterfaceForgotPasswordCall) DoAndReturn(f func(context.Context, *cognitoidentityprovider.ForgotPasswordInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.ForgotPasswordOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceForgotPasswordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GlobalSignOut mocks base method.
func (m *MockAWSCognitoIdentityProviderClientInterface) GlobalSignOut(context1 context.Context, globalSignOutInput *cognitoidentityprovider.GlobalSignOutInput, fns ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.GlobalSignOutOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, globalSignOutInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GlobalSignOut", varargs...)
	globalSignOutOutput, _ := ret[0].(*cognitoidentityprovider.GlobalSignOutOutput)
	err, _ := ret[1].(error)
	return globalSignOutOutput, err
}

// GlobalSignOut indicates an expected call of GlobalSignOut.
func (mr *MockAWSCognitoIdentityProviderClientInterfaceMockRecorder) GlobalSignOut(context1, globalSignOutInput any,
	fns ...any) *MockAWSCognitoIdentityProviderClientInterfaceGlobalSignOutCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, globalSignOutInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GlobalSignOut", reflect.TypeOf((*MockAWSCognitoIdentityProviderClientInterface)(nil).GlobalSignOut), varargs...)
	return &MockAWSCognitoIdentityProviderClientInterfaceGlobalSignOutCall{Call: call}
}

// MockAWSCognitoIdentityProviderClientInterfaceGlobalSignOutCall wrap *gomock.Call
type MockAWSCognitoIdentityProviderClientInterfaceGlobalSignOutCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSCognitoIdentityProviderClientInterfaceGlobalSignOutCall) Return(globalSignOutOutput *cognitoidentityprovider.GlobalSignOutOutput, err error) *MockAWSCognitoIdentityProviderClientInterfaceGlobalSignOutCall {
	c.Call = c.Call.Return(globalSignOutOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSCognitoIdentityProviderClientInterfaceGlobalSignOutCall) Do(f func(context.Context, *cognitoidentityprovider.GlobalSignOutInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.GlobalSignOutOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceGlobalSignOutCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSCognitoIdentityProviderClientInterfaceGlobalSignOutCall) DoAndReturn(f func(context.Context, *cognitoidentityprovider.GlobalSignOutInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.GlobalSignOutOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceGlobalSignOutCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// InitiateAuth mocks base method.
func (m *MockAWSCognitoIdentityProviderClientInterface) InitiateAuth(context1 context.Context, initiateAuthInput *cognitoidentityprovider.InitiateAuthInput, fns ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.InitiateAuthOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, initiateAuthInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InitiateAuth", varargs...)
	initiateAuthOutput, _ := ret[0].(*cognitoidentityprovider.InitiateAuthOutput)
	err, _ := ret[1].(error)
	return initiateAuthOutput, err
}

// InitiateAuth indicates an expected call of InitiateAuth.
func (mr *MockAWSCognitoIdentityProviderClientInterfaceMockRecorder) InitiateAuth(context1, initiateAuthInput any,
	fns ...any) *MockAWSCognitoIdentityProviderClientInterfaceInitiateAuthCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, initiateAuthInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateAuth", reflect.TypeOf((*MockAWSCognitoIdentityProviderClientInterface)(nil).InitiateAuth), varargs...)
	return &MockAWSCognitoIdentityProviderClientInterfaceInitiateAuthCall{Call: call}
}

// MockAWSCognitoIdentityProviderClientInterfaceInitiateAuthCall wrap *gomock.Call
type MockAWSCognitoIdentityProviderClientInterfaceInitiateAuthCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSCognitoIdentityProviderClientInterfaceInitiateAuthCall) Return(initiateAuthOutput *cognitoidentityprovider.InitiateAuthOutput, err error) *MockAWSCognitoIdentityProviderClientInterfaceInitiateAuthCall {
	c.Call = c.Call.Return(initiateAuthOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSCognitoIdentityProviderClientInterfaceInitiateAuthCall) Do(f func(context.Context, *cognitoidentityprovider.InitiateAuthInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.InitiateAuthOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceInitiateAuthCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSCognitoIdentityProviderClientInterfaceInitiateAuthCall) DoAndReturn(f func(context.Context, *cognitoidentityprovider.InitiateAuthInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.InitiateAuthOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceInitiateAuthCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RevokeToken mocks base method.
func (m *MockAWSCognitoIdentityProviderClientInterface) RevokeToken(context1 context.Context, revokeTokenInput *cognitoidentityprovider.RevokeTokenInput, fns ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.RevokeTokenOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, revokeTokenInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RevokeToken", varargs...)
	revokeTokenOutput, _ := ret[0].(*cognitoidentityprovider.RevokeTokenOutput)
	err, _ := ret[1].(error)
	return revokeTokenOutput, err
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockAWSCognitoIdentityProviderClientInterfaceMockRecorder) RevokeToken(context1, revokeTokenInput any,
	fns ...any) *MockAWSCognitoIdentityProviderClientInterfaceRevokeTokenCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, revokeTokenInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockAWSCognitoIdentityProviderClientInterface)(nil).RevokeToken), varargs...)
	return &MockAWSCognitoIdentityProviderClientInterfaceRevokeTokenCall{Call: call}
}

// MockAWSCognitoIdentityProviderClientInterfaceRevokeTokenCall wrap *gomock.Call
type MockAWSCognitoIdentityProviderClientInterfaceRevokeTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSCognitoIdentityProviderClientInterfaceRevokeTokenCall) Return(revokeTokenOutput *cognitoidentityprovider.RevokeTokenOutput, err error) *MockAWSCognitoIdentityProviderClientInterfaceRevokeTokenCall {
	c.Call = c.Call.Return(revokeTokenOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSCognitoIdentityProviderClientInterfaceRevokeTokenCall) Do(f func(context.Context, *cognitoidentityprovider.RevokeTokenInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.RevokeTokenOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceRevokeTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSCognitoIdentityProviderClientInterfaceRevokeTokenCall) DoAndReturn(f func(context.Context, *cognitoidentityprovider.RevokeTokenInput, ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.RevokeTokenOutput, error)) *MockAWSCognitoIdentityProviderClientInterfaceRevokeTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
