// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/service/account"
	"go.uber.org/mock/gomock"
)

// MockAWSAccountClientInterface is a mock of AWSAccountClientInterface interface.
type MockAWSAccountClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAWSAccountClientInterfaceMockRecorder
	isgomock struct{}
}

// MockAWSAccountClientInterfaceMockRecorder is the mock recorder for MockAWSAccountClientInterface.
type MockAWSAccountClientInterfaceMockRecorder struct {
	mock *MockAWSAccountClientInterface
}

// NewMockAWSAccountClientInterface creates a new mock instance.
func NewMockAWSAccountClientInterface(ctrl *gomock.Controller) *MockAWSAccountClientInterface {
	mock := &MockAWSAccountClientInterface{ctrl: ctrl}
	mock.recorder = &MockAWSAccountClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAWSAccountClientInterface) EXPECT() *MockAWSAccountClientInterfaceMockRecorder {
	return m.recorder
}

// GetAccountInformation mocks base method.
func (m *MockAWSAccountClientInterface) GetAccountInformation(context1 context.Context, getAccountInformationInput *account.GetAccountInformationInput, fns ...func(*account.Options)) (*account.GetAccountInformationOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, getAccountInformationInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAccountInformation", varargs...)
	getAccountInformationOutput, _ := ret[0].(*account.GetAccountInformationOutput)
	err, _ := ret[1].(error)
	return getAccountInformationOutput, err
}

// GetAccountInformation indicates an expected call of GetAccountInformation.
func (mr *MockAWSAccountClientInterfaceMockRecorder) GetAccountInformation(context1, getAccountInformationInput any,
	fns ...any) *MockAWSAccountClientInterfaceGetAccountInformationCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, getAccountInformationInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountInformation", reflect.TypeOf((*MockAWSAccountClientInterface)(nil).GetAccountInformation), varargs...)
	return &MockAWSAccountClientInterfaceGetAccountInformationCall{Call: call}
}

// MockAWSAccountClientInterfaceGetAccountInformationCall wrap *gomock.Call
type MockAWSAccountClientInterfaceGetAccountInformationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAWSAccountClientInterfaceGetAccountInformationCall) Return(getAccountInformationOutput *account.GetAccountInformationOutput, err error) *MockAWSAccountClientInterfaceGetAccountInformationCall {
	c.Call = c.Call.Return(getAccountInformationOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAWSAccountClientInterfaceGetAccountInformationCall) Do(f func(context.Context, *account.GetAccountInformationInput, ...func(*account.Options)) (*account.GetAccountInformationOutput, error)) *MockAWSAccountClientInterfaceGetAccountInformationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAWSAccountClientInterfaceGetAccountInformationCall) DoAndReturn(f func(context.Context, *account.GetAccountInformationInput, ...func(*account.Options)) (*account.GetAccountInformationOutput, error)) *MockAWSAccountClientInterfaceGetAccountInformationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
